Translation of Git episode 2
swcarpentry-ja/i18n pull request #107
Opened 2020-07-29 10:34 UTC by rikutakei

Translation of Git episode 2.

I had a minor merge conflict when pulling from the `swcarpentry-ja/i18n ja` branch, so something might be a bit "off".

よろしくおねがいします:slightly_smiling_face:

2020-08-17 00:37 UTC, joelnitta reviewed
Thanks for the translation! I just have a few comments/suggestions.

2020-08-17 00:37 UTC, joelnitta commented on po/git-novice.ja.po
> +"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラの場合、\n"
Did we decide to stick with the original Dracula instead of changing to Doraemon？ (I think Dracula is fine...)

2020-08-17 00:37 UTC, joelnitta commented on po/git-novice.ja.po
> +"変更箇所を「プッシュ」した際に、これらの情報が使われるからです。"
This is a fault of the original lesson, but I don't think the concept of "pushing" has been introduced yet, so 「プッシュ」may be difficult to understand. Probably better to add a parenthetical explanation.
```suggestion
"変更箇所を「プッシュ」した（送った）際に、これらの情報が使われるからです。"
```

2020-08-17 00:37 UTC, joelnitta commented on po/git-novice.ja.po
> +"> 初期設定では、Vim がデフォルトのテキストエディタに設定されています。保存せずに Vim を終了するには、\n"
Missing "for many programs"
```suggestion
"> 多くのソフトの初期設定では、Vim がデフォルトのテキストエディタに設定されています。保存せずに Vim を終了するには、\n"
```

2020-08-21 06:20 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラの場合、\n"
Either is fine with me. Doraemon was a joke for a demo of the first page. They're both a bit childish and fun in my view. This has been an issue discussed at length for the English lessons (and less silly alternatives like a Guacamole recipe have been tried). I get that it's easier to keep the same characters as the English version.

2020-08-21 06:24 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラの場合、\n"
Here's a link to the [thread](https://github.com/swcarpentry/git-novice/issues/277) on the Guacamole lesson if interested. @dpshelio has a demo [here](http://github-pages.ucl.ac.uk/git-novice/).

2020-09-12 15:57 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +msgstr "> ## Vim の終了の仕方"
Glad to see this still in the lessons. I was the one that added it 😄

2020-09-30 04:59 UTC, masamiy reviewed
Great work! My comments are really only suggestions.

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"- \"Git を使うために必要な設定は？\"\n"
This is just to be consistent with R translation style:
```suggestion
"- \"Git を使うために必要な設定は何ですか？\"\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"目的：\n"
I think it will be covered by lang.md file, but in case:
```suggestion
"目標：\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"- \"コンピュータで初めて `git` を使う時に行う設定。\"\n"
Just a style consistency:
```suggestion
"- \"コンピュータで初めて `git` を使うための設定が出来るようになりましょう。\"\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"- \"`--global` 設定フラグの意味を理解する。\"\n"
```suggestion
"- \"`--global` 設定フラグの意味を理解しましょう。\"\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"キーポイント：\n"
Aagin, it can be taken care of by another file, but in case:
```suggestion
"まとめ：\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"コマンドラインでは、Git コマンドは `git 動詞` と入力します。\n"
This is an only suggestion to make it look nicer (to me):
```suggestion
"コマンドラインでは、Git コマンドは `git <動詞>` と入力します。\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +msgstr "*   好みのテキストエディタ、"
```suggestion
msgstr "*   使用したいテキストエディタ、"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラの場合、\n"
I think it maybe nicer to add something around Doracula to make it explicit that he/she is a user of a new laptop. e.g.,
```suggestion
"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラが新しいユーザーの場合、\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"このようにしてコンピュータを設定します："
```suggestion
"以下のようにコンピュータを設定します："
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"> 他のキーと同様に、<kbd>Return</kbd> キーを押すと、\n"
Return key should be okay, but what about Enterキー　or 入力キー or 実行キー ?
```suggestion
"> 他のキーと同様に、<kbd>Return</kbd> キーを押すと、\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +" <kbd>Esc</kbd> キーを押した後に `:q!` と入力してから <kbd>Return</kbd> キーを押してください。\n"
If you decide to change Return to something else, please change here:
```suggestion
" <kbd>Esc</kbd> キーを押した後に `:q!` と入力してから <kbd>Return</kbd> キーを押してください。\n"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"> 保存してから終了するには、 <kbd>Esc</kbd> キーを押してから `:wq` と入力して <kbd>Return</kbd> キーを押してください。"
and here:
```suggestion
"> 保存してから終了するには、 <kbd>Esc</kbd> キーを押してから `:wq` と入力して <kbd>Return</kbd> キーを押してください。"
```

2020-09-30 04:59 UTC, masamiy commented on po/git-novice.ja.po
> +"> この場合、プロキシの設定もしなければなりません：\n"
```suggestion
"> この場合、プロキシの設定が必要です：\n"
```

2020-09-30 07:10 UTC, joelnitta commented on po/git-novice.ja.po
> +"目的：\n"
Actually, "Objectives" and the other header words ("Teaching", "Exercises", etc) shouldn't be translated at all ([see the update to quickstart.md](https://github.com/swcarpentry-ja/i18n/commit/da680b9ffcff91d473a0b3bd1f9e0af0a9a174e0?short_path=018e220#diff-018e220b50f876168d6d1d4dbf52ce84)). I think @TomKellyGenetics can fix this in the PR (unless @rikutakei you want to do it).

2020-10-01 15:19 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"キーポイント：\n"
See updated guide for translations.

```suggestion
keypoints：\n"
```

2020-10-01 15:20 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"目的：\n"
```suggestion
"objectives：\n"
```

2020-10-01 15:21 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"質問：\n"
```suggestion
"questions：\n"
```

2020-10-01 15:24 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"objectives：\n"
```suggestion
"objectives: \n"
```

2020-10-01 15:24 UTC, TomKellyGenetics requested changes

2020-10-01 15:24 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"questions：\n"
```suggestion
"questions:\n"
```

2020-10-01 15:25 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +keypoints：\n"
```suggestion
"keypoints:\n"
```

2020-10-01 15:29 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"目的：\n"
@joelnitta fixed 😄

2020-10-11 02:37 UTC, rikutakei commented on po/git-novice.ja.po
> +"ここでの「動詞」は、Git に何をさせたいのかを表します。ドラキュラの場合、\n"
I think it'll be a simple `sed` if we decide to change the names; going to leave this as is for now.

2020-10-11 02:41 UTC, rikutakei commented on po/git-novice.ja.po
> +"> 他のキーと同様に、<kbd>Return</kbd> キーを押すと、\n"
It can be Enter if we want to, but I though I'd stick with the Return key here, as the original lesson refers to it as Return

2020-10-11 02:45 UTC, rikutakei commented
I have added everyone's suggestions, so I think this should be good for merging

2020-10-11 04:18 UTC, joelnitta approved these changes

2020-11-10 18:17 UTC, TomKellyGenetics requested changes

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"-   \"`git config` と `--global` オプションを使い、ユーザー名、メールアドレス、エディタ、その他の設定を行う。\"\n"
```suggestion
"-   \"`git config` と `--global` オプションを使い、ユーザー名\n"
"メールアドレス、エディタ、その他の設定を行う。"
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"- \"Git を使うために必要な設定は何ですか？\"\n"
```suggestion
"- Git を使うために必要な設定は何ですか？\n"
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"- \"コンピュータで初めて `git` を使うための設定が出来るようになりましょう。\"\n"
```suggestion
"- コンピュータで初めて `git` を使うための設定が出来るようになりましょう。\n"
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"- \"`--global` 設定フラグの意味を理解しましょう。\"\n"
```suggestion
"- `--global` 設定フラグの意味を理解しましょう。\n"
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"> [こちらの GitHub ページ](https://help.github.com/articles/dealing-with-line-endings/)を参照してください。"
```suggestion
"> [こちらの GitHub ページ](https://help.github.com/articles/dealing-with-line-endings/)\n"
"を参照してください。"
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"For these lessons, we will be interacting with [GitHub](https://github.com/) and so the email address used should be the same as the one used when setting up your GitHub account. If you are concerne
```suggestion
"For these lessons, we will be interacting with [GitHub](https://github.com/) "
"and so the email address used should be the same as the one used when "
"setting up your GitHub account. If you are concerned about privacy, please "
"review [GitHub's instructions for keeping your email address private][git-"
"privacy]. \n""
```

2020-11-10 18:17 UTC, TomKellyGenetics commented on po/git-novice.ja.po
> +"If you elect to use a private email address with GitHub, then use that same email address for the `user.email` value, e.g. `username@users.noreply.github.com` replacing `username` with your GitHub o
```suggestion
"If you elect to use a private email address with GitHub, then use that same "
"email address for the `user.email` value, e.g. `username@users.noreply."
"github.com` replacing `username` with your GitHub one. You can change the "
"email address later on by using the `git config` command again."
```

2020-11-10 18:18 UTC, TomKellyGenetics approved these changes
Great job Riku, let's see if we can trigger GitHub Actions: https://github.com/swcarpentry-ja/i18n/actions?query=workflow%3ARender-Webpages

2020-11-10 18:18 UTC, merged

2020-11-11 07:07 UTC, TomKellyGenetics commented
Had to mess with the script and formatting but now it's builds webpages *automatically* when a commit is pushed to `ja` branch. This _includes_ PRs.

Page updated by bot:
https://swcarpentry-ja.github.io/git-novice/ja/_episodes/02-setup/index.html

GitHub Actions instance (runs 3 lessons simultaneously).
https://github.com/swcarpentry-ja/i18n/actions/runs/357290157

Long story on how to give it permissions and make it run in an empty docker container should work like magic from now on.