Translate OpenRefine: Setup
swcarpentry-ja/i18n pull request #154
Opened 2021-07-30 21:15 UTC by kozo2

See also #151

2021-08-01 23:47 UTC, masamiy commented
Thanks @kozo2 , I will have a look by the end of next week.

2021-08-09 06:14 UTC, masamiy requested changes
Thanks Kozo for your translation! I think it is good. Please add a small space between alphabet and Japanese characters throughout the lesson. Other than that, I left a few suggestions. Please have a look.

2021-08-09 06:14 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "このレッスンを実行するには、OpenRefineをインストールし、データファイルをダウンロードする必要があります。"
Suggestion: 
 Instead of このレッスンを実行するには
how about このレッスンは
?

2021-08-09 06:14 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "### OpenRefineのインストールと実行"
OpenRefine の
A small space between alphabet and Hiragana is required and it applies throughout the lesson.

2021-08-09 06:14 UTC, masamiy commented on po/lc-open-refine.ja.po
> +"OpenRefineをインストールするには、ダウンロードしたファイルをコンピューターの永続的な場所に解凍します。\n"
Instead of 永続的な場所
how about 常に存在するディレクトリ 
?

2021-08-09 06:14 UTC, masamiy commented on po/lc-open-refine.ja.po
> +"* 「Javaが組み込まれたWindowsキット」および「Macキット」の選択肢には、パッケージの一部としてJavaが含まれています。\n"
Suggestion: What about connecting this sentence with the next by saying Javaが含まれているので？

2021-08-09 06:14 UTC, masamiy commented on po/lc-open-refine.ja.po
> +"[Windows](https://groups.google.com/g/openrefine/search?q=windows)、[macOS](https://groups.google.com/g/openrefine/search?q=macOS)、または[Linux](https://groups.google.com/g/openrefine/search?q=linux)に関連
... 関連するスレッドのように, 検索するときはあなたの問題に最も関連する回答を見つけるためにオペレーティングシステムの情報を含めてください。

2021-08-13 11:43 UTC, kozo2 commented on po/lc-open-refine.ja.po
> +"[Windows](https://groups.google.com/g/openrefine/search?q=windows)、[macOS](https://groups.google.com/g/openrefine/search?q=macOS)、または[Linux](https://groups.google.com/g/openrefine/search?q=linux)に関連
I reflected the suggestion at https://github.com/swcarpentry-ja/i18n/pull/154/commits/3f139c9682a9957c79f4622e979126a00a8d1131

2021-08-13 11:44 UTC, kozo2 commented on po/lc-open-refine.ja.po
> +"* 「Javaが組み込まれたWindowsキット」および「Macキット」の選択肢には、パッケージの一部としてJavaが含まれています。\n"
I reflected the suggestion at https://github.com/swcarpentry-ja/i18n/pull/154/commits/18431e2ba442c6992163b13a7802142dc086bfb7

2021-08-13 11:47 UTC, kozo2 commented on po/lc-open-refine.ja.po
> +msgstr "このレッスンを実行するには、OpenRefineをインストールし、データファイルをダウンロードする必要があります。"
I reflected the suggestion at https://github.com/swcarpentry-ja/i18n/pull/154/commits/6193b63cf4bb04f3921344aa8d4777a72ccc824b

2021-08-13 11:58 UTC, kozo2 commented on po/lc-open-refine.ja.po
> +"OpenRefineをインストールするには、ダウンロードしたファイルをコンピューターの永続的な場所に解凍します。\n"
I reflected the suggestion at https://github.com/swcarpentry-ja/i18n/pull/154/commits/7bda2fc768257bce28b3a92944823c9a1f95454a

2021-08-14 11:45 UTC, kozo2 commented on po/lc-open-refine.ja.po
> +msgstr "### OpenRefineのインストールと実行"
I added small spaces between alphabet and Hiragana at https://github.com/swcarpentry-ja/i18n/pull/154/commits/97193e8d3164c1696dc102bddb1b4ab4f5b31d4c

2021-08-14 11:59 UTC, kozo2 commented
@masamiy I have reflected all the changes you requested in the po file.

2021-08-21 00:50 UTC, masamiy approved these changes
Thanks Kozo!

2021-09-10 23:27 UTC, naganeayu commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
`msgstr "* [III Sierra、 MS Excel と OpenRefine を利用して、可能性のある典拠ファイルの件名標目を特定する](http://epublications.marquette.edu/lib_fac/81/)"
`
@masamiy ↑の訳にご意見伺えますでしょうか…

2021-09-12 00:34 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
はい。ご確認有り難うございます。えー、[III Sierra、MS Excel と OpenRefine による、典拠データ (Authority workのことは日本語だとこうなるのでしょうか？) となりうるヘッディング（エントリーとしても良いかも）の特定] って感じでしょうか？
カタログデータに特化した文献のようですね。
ご意見ございましたらぜひ！

2021-09-12 01:39 UTC, naganeayu commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
@masamiy  コメントありがとうございます！「図書館用語集4訂版」を確認したところ、以下の通りでした。

- 典拠ファイル（Authority file, authority list）
- 標目（heading）

Authority workって具体的に何でしょうか。。Authority fileを作成する作業なのかな、と思ったのですが。

2021-09-12 10:48 UTC, joelnitta commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
全く専門外ですが、２個参考になりそうな資料がありました：

- 多分、[wikipediaによると](https://ja.wikipedia.org/wiki/%E5%85%B8%E6%8B%A0%E7%AE%A1%E7%90%86)、authority work = authority control = 典拠管理
- ここでいう「heading」は私に意味が分かりませんが、[元々リンクされているpdf](https://epublications.marquette.edu/cgi/viewcontent.cgi?article=1082&context=lib_fac)を読むと何かヒントがあるかも？9ページにあるスクリーンショットを見ると、「典拠」その物とあまり変わらない気がします。

2021-09-13 00:22 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
私もカタロガーではないので、文献をざっと読んで想像したところによると、
例えば、Yamaguchi のバリエーションとして Yamaguti や Yamaguci がデータの中に混在していると、検索で引っかからないものが出ますよね。そういうのを防ぐための作業をしているようです。
カタログデータ内にはすでに色々なバリエーションが存在しているので、CINAHL Heading みたいなのを作って、それに存在しているエントリーをリンクするようなイメージです。なので、authority work というのは、カタログデータ管理のことで、(それを典拠管理という？) Heading は Controlled vocabulary のことだというイメージです。 
典拠管理のための Controlled vocabulary を特定するための作業を Sierraや Open Refine を使ってやってみたという感じ。

2021-09-13 10:13 UTC, naganeayu commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
コメントありがとうございます！以下で如何でしょうか？

[III Sierra、MS Excel と OpenRefine による、典拠データとなりうる標目の特定]

2021-09-14 05:25 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
いい感じ！と私は思いますが、念のため、私が唯一存じ上げる日本の図書館員の方に聞いてみます。

2021-09-15 00:53 UTC, masamiy commented on po/lc-open-refine.ja.po
> +msgstr "* [Identifying potential headings for Authority work using III Sierra, MS Excel and OpenRefine](http://epublications.marquette.edu/lib_fac/81/)"
「III Sierra、MS Excel と OpenRefine による、典拠データとなりうる標目の特定」
でもよいと思いますし
「 III Sierra, MS Excel and OpenRefineを利用した典拠データの標目となりうる語の特定」
とのことです。

2021-10-03 00:19 UTC, naganeayu approved these changes

2021-10-03 00:20 UTC, merged