Translate 11. Licensing
swcarpentry-ja/i18n pull request #155
Opened 2021-08-01 08:01 UTC by kozo2

#71 is the issue number.

2021-08-05 06:06 UTC, joelnitta reviewed
Thanks! Please note that words before colons like `title:` etc should generally not be translated in the PO file (they are translated from an overall list separately).

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"タイトル: ライセンスの供与\n"
Words before `:` are automatically translated and should not be changed in the PO file.
```suggestion
"title: ライセンスの供与\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"講義: 5\n"
```suggestion
"teaching: 5\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"演習: 0\n"
```suggestion
"exercises: 0\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"質問:\n"
```suggestion
"questions:\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"目標:\n"
```suggestion
"objectives:\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"キーポイント:\n"
```suggestion
"keypoints:\n"
```

2021-08-05 06:06 UTC, joelnitta commented on po/git-novice.ja.po
> +"自分のソフトウェアもGPLライセンスの下で公開するしなければなりません; "
typo?
```suggestion
"自分のソフトウェアもGPLライセンスの下で公開しなければなりません; "
```

2021-08-09 08:46 UTC, kozo2 commented
@joelnitta Thanks for your comment!
I committed all your suggestions.

2021-10-02 01:59 UTC, joelnitta approved these changes

2021-10-06 04:18 UTC, masamiy requested changes
Thank you for the translation! I made some suggestions. Please have a look.

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"自分のソフトウェアもGPLライセンスの下で公開しなければなりません; "
```suggestion
"自分のソフトウェアも GPL ライセンスの下で公開しなければなりません; "
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"実際には、2~3個のライセンスが圧倒的に人気があります。\n"
```suggestion
"実際には、2~3 種類のライセンスが圧倒的に人気があります。\n"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"どういった権利がどういう条件で供与されるかはライセンス毎に異なります。\n"
```suggestion
"どういった権利がどういう条件で供与されるかはライセンス毎に異なりますが\n"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"ですが大抵大きな違いはありません。"
```suggestion
"大抵の場合大きな違いはありません。"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"結局のところ、重要なのはライセンスが何であるかについて明確な声明があるということです。\n"
```suggestion
"結局のところ、重要なのはライセンスが何であるかについて明確なステートメントがあるということです。\n"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +msgstr "> ## どのライセンスをすでに甘受しているのでしょうか?"
```suggestion
msgstr "> ## どのライセンスをすでに受け入れているのでしょうか?"
```
甘受 may be okay, but based on https://kotobank.jp/word/%E7%94%98%E5%8F%97-470071, it sounds like 'reluctantly accept'. I think emotionally neutral expression is better.

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"> オープンソースソフトウェアとしてリリースされています。以下のリストからGitHub上のプロジェクトを選択するか、"
```suggestion
"> オープンソースソフトウェアとしてリリースされています。以下のリストから GitHub 上のプロジェクトを選択するか、"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"> - [Jupyter](https://github.com/jupyter)、我々が用いるであろうウェブベースのPythonノートブックの背後にあるプロジェクト\n"
```suggestion
"> - [Jupyter](https://github.com/jupyter)、我々が用いるであろうウェブベースの Python ノートブックの背後にあるプロジェクト\n"
```

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +"- \"作品にどのようなライセンス情報を含める必要がありますか?\"\n"
```suggestion
"- \"著作物にどのようなライセンス情報を含める必要がありますか?\"\n"
```
作品 sounds like a visual art (just to me?), but it refers to a script/software you have developed here I understand. It is hard one. How would you usually call your 'work'?

2021-10-06 04:18 UTC, masamiy commented on po/git-novice.ja.po
> +msgstr "* 特許権に取り組みたいかどうか。"
```suggestion
msgstr "* 特許権をに取り組みたいかどうか。"
```
I think "address patent rights" needs more clarity. I logged [an issue](https://github.com/swcarpentry/git-novice/issues/844). As when the issue will be reviewed is unknown, I leave this translation as it is for now.

2021-12-01 17:07 UTC, kozo2 commented on po/git-novice.ja.po
> +"- \"作品にどのようなライセンス情報を含める必要がありますか?\"\n"
I replaced 作品 to 著作物.

2021-12-01 17:14 UTC, kozo2 commented
@masamiy Thank you for your suggestions!
I have committed all your suggestions other than https://github.com/swcarpentry-ja/i18n/pull/155#discussion_r720774865 .
Let me know if I can solve https://github.com/swcarpentry-ja/i18n/pull/155#discussion_r720774865 as well.

2021-12-04 22:32 UTC, joelnitta commented
As we have no idea when @masamiy's [issue](https://github.com/swcarpentry/git-novice/issues/844) will be resolved, I think we should accept the translation as it is now (we can add a linked issue here to remind ourselves to fix it in the future).

2025-05-24 11:57 UTC, closed without merging