Translation: Library Carpentry OpenRefine Episode 1
swcarpentry-ja/i18n pull request #177
Opened 2021-10-17 05:06 UTC by naganeayu

2021-10-18 06:21 UTC, masamiy requested changes
Thank you for your work!
I think I have reviewed at stuff I should look. If there are specific sections/sentences you would like me to have a look, please do let me know.

2021-10-18 06:21 UTC, masamiy commented on README.md
> +ツイッターで[swcarpentry-ja](https://twitter.com/swcarpentry_ja)も更新の発表をやっています。ぜひフォローし
```suggestion
ツイッター[swcarpentry-ja](https://twitter.com/swcarpentry_ja)もやっています。ぜひフォローし
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +ここでは、あなたが、GitとGitHubについて知っているという仮定をしています。
```suggestion
ここでは、あなたが、Git と GitHub について知っていると仮定ます。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +もしあなたが、レッスン自体の問題に気づいたら、英語のレッスンに対して、issueをたてたり、プルリクエストを送ってください。
```suggestion
もしあなたが、レッスン自体の問題に気づいたら、英語のレッスンに対して、issue をたてたり、プルリクエストを送ってください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +もし、gitをインストールするのに手助けが必要ならば、[gitのインストールガイド](docs/git.md)を読んでみてください
```suggestion
もし、gitをインストールするのにサポートが必要ならば、[gitのインストールガイド](docs/git.md)を読んでみてください
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +オリジナルのテキストの追跡を行うことができ、オリジナルのレッスンが更新されたときに、変更され翻訳が必要とされる部分を正確に把握することができます。
```suggestion
オリジナルテキストの追跡を行うことができ、オリジナルのレッスンが更新されたときに、変更され翻訳が必要とされる部分を正確に把握することができます。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +POファイルを編集しても、翻訳されたWebサイトができあがるわけではありません。[メンテナーと管理者ガイド](docs/admin.md)で述べられているよう
```suggestion
PO ファイルを編集しても、翻訳された Web サイトができあがるわけではありません。[メンテナーと管理者ガイド](docs/admin.md)で述べられているよう
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +んでいます)へ翻訳するのを容易にするために必要なファイルやツールをホストするためにあります。また、英語とスペイン語のレッスンの多言語化をしてマージするためでもあります。
I am not 100% sure of the English version of the sentence here, but:
```suggestion
んでいます)へ翻訳するのを容易にするために必要なファイルやツールをホストするためのものです。また、英語やスペイン語など他言語のレッスンをマージするためでもあります。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +リポジトリは、[ソフトウェアカーペントリー](https://software-carpentry.org/)のレッスンを英語から他の言語(現在日本語に取り組
Do we have a plan to translate lessons other than Japanese?

リポジトリは、[ソフトウェアカーペントリー](https://software-carpentry.org/)のレッスンを英語から他の言語(**現在日本語に取り組...** sounds like we will work on a different language in the future. 
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +ソフトウェアカーペントリーのメインのウェブサイトが他の言語と一緒にホストされ互換性があり、英語のレッスンの新しいリリースに合わせて日本語のレッスンも最新に維持
```suggestion
私たちは、日本語のレッスンが互換性を持って他の言語のレッスンと共にソフトウェアカーペントリーのメインのウェブサイトから提供され、英語のレッスンのアップデートに伴い日本語のレッスンもアップデート出来るようにすることを計画しています。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +私達は、ソフトウェアカーペントリーのオリジナルのレッスンを改定するのではなく、レッスを翻訳（そして最新の状態に維持）をしています。
```suggestion
私達は、ソフトウェアカーペントリーのオリジナルのレッスンを変更するのではなく、レッスを日本語に翻訳（そして最新の状態を維持）する作業をしています。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +各レッスンのテキストを直接翻訳するのではなく、翻訳には、[PO ファイル](https://www.gnu.org/software/gettext/manu
```suggestion
翻訳作業を行う際は、各レッスンのテキストを直接翻訳するのではなく、[PO ファイル](https://www.gnu.org/software/gettext/manu
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +ice)は、複数の markdown形式のドキュメントで構成され、日本語の翻訳に関しては１つの `git-novice.ja.po` というPOファイルがあります。これにより、手
```suggestion
ice)は、複数の markdown形式のドキュメントで構成され、日本語の翻訳に関しては１つの `git-novice.ja.po` という PO ファイルがあります。これにより、
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +動ではなく、
```suggestion
容易に、
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +**これは、翻訳者からの手助けが最も必要なタスクです!**
```suggestion
**ヘルプが最も必要なタスクがここです!**
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +前提としています。あなたは、そのレッスンの翻訳に貢献したいとします。
```suggestion
前提としています。あなたが、そのレッスンの翻訳に貢献したいとします。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +1. 個人のGitHubアカウントで、このリポジトリの"フォーク"を作成します。
```suggestion
1. 個人の GitHub アカウントで、このリポジトリの"フォーク"を作成します。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +2. 個人のアカウント(GitHubUserなど)で、このリポジトリをクローンします。これは、翻訳ファイルのバージョン管理するためのローカルコピーです
```suggestion
2. 個人のアカウント(GitHubUser など)で、このリポジトリをクローンします。これは、翻訳ファイルのバージョン管理するためのローカルコピーです。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +3. サブモジュールを使えるようにする.
```suggestion
3. サブモジュールを使えるようにします。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +このリポジトリはすでに、レッスンの翻訳ファイルが含まれています。翻訳に貢献したいときには、 `po` ディレクトリの中の `<レッスン名>.<言語>.po`
```suggestion
このリポジトリはすでに、レッスンの翻訳ファイルが含まれています。貢献は、 `po` ディレクトリの中の `<レッスン名>.<言語>.po` 
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +例えば `git-novice.ja.po` に貢献することができます。
```suggestion
例えば `git-novice.ja.po` から出来ます。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +4. POファイルを編集します。[ガイドラインに従って](docs/rules.md), 頻繁に変更をコミットし、十分だとおもったらpull request
```suggestion
4. POファイルを編集します。[ガイドラインに従って](docs/rules.md)、頻繁に変更をコミットし、作業が完了したら pull request 
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +を投稿してください。
```suggestion
を送ってください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +5. 正確を期すために、あなたのPRについて、レビューが行われます。レビューがパスするまで、編集を続けます。そのようなときは、まずはじめに、
```suggestion
5. 正確を期すために、あなたの PR はレビュアーがレビューします。レビューがパスするまで、編集を続けます。そのようなときは、まずはじめに、
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +組織のリポジトリに対する変更を pull してください。
```suggestion
swcarpentry-ja/i18n.git リポジトリに対する変更を pull してください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +いくつかのメモ:
```suggestion
注意事項:
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +あなたの変更を含めた翻訳されたバージョンを生成します。これは、`locale/<lang>/<lesson>`, 例,
```suggestion
あなたの変更を含めた翻訳バージョンを生成します。これは、`locale/<lang>/<lesson>`, 例,
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +## メインの英語のレッスンが新しくリリースされたら、レッスンを更新するのに貢献する
```suggestion
## 翻訳済レッスンの英語バージョンがアップデートされた場合の貢献
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +[レッスン更新時のガイド](docs/updating.md)を見てください。
```suggestion
[レッスン更新時のガイド](docs/updating.md)を参照してください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +レッスン間で用語が一貫して使われていることを確認するために
```suggestion
レッスンでは一貫した用語が使用されているようにします。 
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> + があります。必要に応じてこれを参照したり更新したりしてください。
```suggestion
必要に応じて[技術用語のリスト](https://github.com/swcarpentry-ja/i18n/wiki/Glossary-for-technical-terms)を参照したり更新したりしてください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +[技術用語のリスト](https://github.com/swcarpentry-ja/i18n/wiki/Glossary-for-technical-terms)
Suggest to delete.

2021-10-18 06:21 UTC, masamiy commented on README.md
> +一貫性を担保するために、日本語に翻訳されない概念などの標準化された取り扱いについては、 [カルチャーノート](docs/CultureNotes.md) を参
```suggestion
一貫性を保持するために、日本語に翻訳されない概念などの標準化された取り扱いについては、 [カルチャーノート](docs/CultureNotes.md) を参
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +進捗と、ゴールを記録するために[変更履歴](docs/ChangeLog.md)を持っています。
```suggestion
進捗と、達成度を記録するために[変更履歴](docs/ChangeLog.md)があります。
```
FYI, I could not access to the ChangeLog.md[https://github.com/swcarpentry-ja/i18n/blob/ja/docs/ChangeLog.md] from the original doc. Is it just me?

2021-10-18 06:21 UTC, masamiy commented on README.md
> +[メンテナーと管理者のガイド](docs/admin.md) を見てください
```suggestion
[メンテナーと管理者のガイド](docs/admin.md) を参照してください。
```

2021-10-18 06:21 UTC, masamiy commented on README.md
> +ここは、翻訳を進める上で発生する疑問に関して質問するのに最適の場所です。
```suggestion
翻訳作業中に生じた疑問などは、ここから質問してください。
```

2021-10-19 13:19 UTC, naganeayu commented
Wrong branch & PR

2021-10-19 13:19 UTC, closed without merging