revised:L1 r-novice-gapminder
swcarpentry-ja/i18n pull request #32
Opened 2018-11-26 10:47 UTC by rkkmk

https://github.com/swcarpentry-ja/i18n/commits?author=rkkmk

2018-11-30 08:22 UTC, joelnitta requested changes
Thanks! This looks great. I found some spots where I think the translation needs fixing - please see my suggestions. In addition I found a few issues that need to be corrected in the main DC/SWC repo, but noting them here first.

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"科学は複数の段階からなる作業です：実験を計画したら、データを収集し、\n"
The original text implies three linear steps: plan the experiment, collect the data, do the analysis. I think we want to emphasize that the first two steps are done. How about:
```suggestion
"科学は複数の段階からなる作業です：実験を計画し、データを収集したら、\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"開発環境です。RStudioには、全てのプラットフォーム（サーバーも含む）で起動できるエディタ\n"
The English distinguishes between including an editor and being able to run on all platforms. We may also want to add the definition of IDE (even though this is lacking in the English version).
```suggestion
"開発環境です。RStudioは、全てのプラットフォーム（サーバーも含む）で起動できること、\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"が入っていて、プロジェクト管理やバージョン管理にも対応しているなど、良いところが\n"
```suggestion
"エディタが組み込まれていることや、プロジェクト管理やバージョン管理にも対応しているなど、\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"いっぱいがあります。"
```suggestion
"良いところがいっぱいあります。"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"修正した行を送るコマンドを走らせるために、RStudioのショートカットキーを使う。\n"
```suggestion
"修正した行など送るコマンドを走らせるために、RStudioのショートカットキーを使う。\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "  * ファイル／プロット／パッケージ／ヘルプ／ビューワー（右下のタブ形式）"
Do these menu items appear in English or Japanese when RStudio is run on a computer with region set to Japan? If English, I think we should leave them untranslated (but include explanations of what they mean in parentheses).

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"するとRは、「[1]」の後に回答を表示します。詳しくは後で説明するので、\n"
We should clarify that "this" refers to the [1], not the rest of the output.
```suggestion
"するとRは、「[1]」の後に回答を表示します。「[1]」については後で説明するので、\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> -"The text after each line of code is called a\n"
This is something I think needs to be corrected in the original. The only thing that defines comments is that they come after the hashmark (on the same line), not placement "before" or "after" code.

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"> かもしれません。すると、二つの数がRで同じように表示されても\n"
```suggestion
"> なので、二つの数がRで同じように表示されても\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"> コンピュータは、小数点以下の数を限られた精度でしか示せない\n"
The "may" here means "be able to", not "maybe"
```suggestion
"> コンピュータは、小数点以下の数を限られた精度でしか示せません。\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> -"variables and functions can have vectors as values. In contrast to physics and\n"
Yet another issue with the original English. I wouldn't say functions can have vectors as values. Rather, (if they are vectorized) they can take vectors as arguments.

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"Rのベクトルは、同じデータ型のある順番を持つ値の集合として示されます。例えば："
"describes" here means "defined as", not "shows".
```suggestion
"Rのベクトルは、同じデータ型のある順番を持つ値の集合として定義されています。例えば："
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"これについて、CRAN (the comprehensive R archive network)上にある\n"
"As of this writing" means "currently"
```suggestion
"今現在CRAN (the comprehensive R archive network)上にある\n"
```

2018-11-30 08:22 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"  ここで、`packagename`は、用いるパッケージ名です。\n"
Important to mention including quotes around the package name here. The fact that it's not needed for `library()` is probably something that should be clarified in the original lesson.
```suggestion
"  ここで、`packagename`は、用いる引用符付きのパッケージ名です。\n"
```

2018-11-30 12:42 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> -"variables and functions can have vectors as values. In contrast to physics and\n"
I thought this description is related to the fact that "R has no 0-dimensional, or scalar types. Individual numbers or strings, which you might think would be scalars, are actually vectors of length one."
(quoted from http://adv-r.had.co.nz/Data-structures.html)

2018-11-30 12:56 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"開発環境です。RStudioには、全てのプラットフォーム（サーバーも含む）で起動できるエディタ\n"
How about adding IDE next to the word? Then, the reader got interested in can look it up online. (I couldn't come up with a concise definition which wouldn't make the sentence too long...) 

```suggestion
"総合開発環境（IDE: Integrated Development Environment）です。RStudioは、全てのプラットフォーム（サーバーも含む）で起動できること、\n"
```

2018-11-30 12:59 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"いっぱいがあります。"
Are you suggesting we should remove 良いところが from line 931 and move to 932??

2018-11-30 13:04 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> コンピュータは、小数点以下の数を限られた精度でしか示せない\n"
I agree with your suggestion. Then かもしれません。on the line 2191 should also be removed at the same time?

2018-12-03 07:55 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> -"variables and functions can have vectors as values. In contrast to physics and\n"
Actually, I don't think that quote from Advanced R directly applies here. The problem is that the original version conflates arguments to functions with functions themselves. At any rate, let's leave the translation as it is, and file an issue to fix this in the main SWC lesson repo.

2018-12-03 07:55 UTC, joelnitta approved these changes

2018-12-04 15:27 UTC, merged

2018-12-04 15:34 UTC, TomKellyGenetics commented
These changes have been added to the repository :-)