Translation of vectorization - lesson 6
swcarpentry-ja/i18n pull request #39
Opened 2019-07-02 22:24 UTC by atusy

2019-07-24 11:28 UTC, rikutakei requested changes
良いと思います :blush: 
僕が個人的に好む翻訳が入ってると思いますので、 「これ間違ってるかも」と感じたら他の方にも見てもらえるように＠で他の方をタグして下さい。

コメントした部分を変更してくれれば、マージします。

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"- \"ベクトルの全要素をまとめて操作する方法がわかりますか？\"\n"
ここは、習っている方が質問をしているので、習っている方の目線で翻訳するほうがいいかもしれません。
例えば、「どうやってベクトルの全要素をまとめて操作するの？」。
まだ説明していないのですが、SWCでは「上から目線」または威圧的な表現の仕方を極力しないように心がけているので、難しいのですが、誰が読んでもネガティブな印象が出ないような翻訳の仕方をお願いします。

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"Rの関数はほとんどがベクトル化されているので、関数はベクトルの全ての要素を操作してくれ、ベクトルの要素ごとにいちいちループする必要がありません。\n"
Rの関数はほとんどがベクトル化されて~~いるので~~**おり**、関数はベクトルの全ての要素を**最初から**操作してくれ**るので**、ベクトルの要素ごとにいちいちループする必要がありません

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "積はベクトルの要素ごとに実行されます。"
**上の例では**積はベクトルの要素ごとに実行されま~~す~~**した**

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "`x` の各要素が対応する `y`の要素に足されます。"
**この場合**`x` の各要素が対応する `y`の要素に足されます

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> >   100万人単位の人口を年ごとにプロットして、作図能力を新たにしましょう。\n"
ここは多分、このエピソードの前にやった`ggplot`系のレッスンで覚えた事をもう一回やって、「作図能力を復習しよう」みたいなことが言いたかったんだと思います。
もう一回お願いします

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> ## Tip: 論理ベクトルに使える便利な関数数点"
最後にある「数点」は必要なのでしょうか？
数点＝someでしたら、「論理ベクトルに使える**いくつかの**便利な関数~~数点~~」
someからotherに変わっちゃうんですけど、「**その他の**論理ベクトルに使える便利な関数~~数点~~」などがあります。

数点でも間違っていないとは思うのですが、他の方の意見が聞きたいです
@joelnitta @rkkmk

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 以下を実行すると何が起きるか書き出して下さい:\n"
以下を実行すると何が起きるか書~~き出し~~**い**て下さい

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 思った通りの出力が得られましたか？違っていたことがあれば、ヘルプを参照しましょう。\n"
思った通りの出力が得られましたか？違っていたことがあれば、ヘル~~プ~~**パーになぜ間違っていたか聞いてみ**~~参照し~~ましょう。

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 以下を実行すると何が起きるか書き出して下さい:\n"
上記参照

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 以下の分数の数列の総和が知りたいとします:\n"
以下の分数の数列の総和~~が知りたいとし~~**に興味があり**ます

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> これをタイピングするのは退屈な上に、nが多きいと不可能です。\n"
これをタイ~~ピング~~**プ**するのは~~退屈~~**面倒**な上に、nが多きいと不可能です

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 以下の分数の数列の総和が知りたいとします:\n"
上記参照

2019-07-24 11:28 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これをタイピングするのは退屈な上に、nが多きいと不可能です。\n"
上記参照

2019-07-24 22:53 UTC, atusy commented
ありがとうございます．今日か明日には修正できると思います．
Rのヘルプのことをヘルパーと呼ぶのは変だなあと思っていたのですが，これはひょっとしてSWCのスタッフのことでしょうか？

2019-07-24 23:10 UTC, rikutakei commented
> Rのヘルプのことをヘルパーと呼ぶのは変だなあと思っていたのですが，これはひょっとしてSWCのスタッフのことでしょうか？

そうです。
SWCを実際にやる際には、公式のインストラクターと複数人のヘルパーがクラスで教える様になっています。
インストラクター、もしくはインストラクター監修の元、ヘルパーの一人が講義を行い、残りのヘルパー達が生徒達のトラブルシューティングに回ります。
こうしないと、なにか問題が起こる度に講義を中断しないといけなくなるので、講義に使う時間がすぐに無くなっちゃうんです。

2019-07-25 05:53 UTC, atusy commented on po/r-novice-gapminder.ja.po
> +msgstr "> ## Tip: 論理ベクトルに使える便利な関数数点"
数点がなくても通じそうですね

2019-07-25 05:56 UTC, atusy commented on po/r-novice-gapminder.ja.po
> +"> >   100万人単位の人口を年ごとにプロットして、作図能力を新たにしましょう。\n"
能力そのものを学ぶわけではないので，「作図能力を復習しよう」にします

2019-07-25 05:59 UTC, atusy commented
ありがとうございます．
修正しました．私が思ったことがあれば Review に返信し，なければ指摘部分を反映の上 resolve にしました．

2019-07-25 08:14 UTC, rikutakei approved these changes

2019-07-25 08:14 UTC, merged