<Lesson 6: translated 2,3,4,5,6,7,15,16>
swcarpentry-ja/i18n pull request #42
Opened 2019-07-21 03:11 UTC by rkkmk

2019-07-25 10:04 UTC, rikutakei reviewed
まだレビューは終わってないんですが、とりあえずいくつか見てみました。

いい感じです。

たまに「もの」とか「これ」というような曖昧な表現が入っているので、読みにくくなっているところがいくつかありました。具体的に何のことを説明しているのかが分かるようにしてくれればもっと良くなります。

いくつか翻訳が難しい単語があったので、後ほどイシューでも開いてみようかと思います。

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"最終的には、全てが少し混ざり合ってまとまっていくものです。"
コンマが少し多い気がします。

科学的なプロセスは徐々に進んでいくもので、多くのプロジェクトは計画性のないメモ・いくつかのコードから始まり、草案ができ、最終的には全てが少し混ざり合ってまとまっていくものです

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"使ったコードを紐づけるのに、多分時間がいっぱいかかる"
「数字」ではなくて「図形」ではないでしょうか？

探しているものを見つけたり、正しい~~数字~~**図形**とそれを生成するために使ったコードを紐づけるのに、~~多分~~時間が~~いっぱい~~かか~~る~~**ります**

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "うまいプロジェクトのレイアウトは、結局のところ、自分自身を楽にする"
~~うまい~~**上手な**プロジェクトのレイアウトは、結局のところ、自分自身を楽に~~する~~**してくれます**

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"* しばらく手をつけていなくても、プロジェクトのバックアップを簡単に選べる"
データの「バックアップ」ではなくて、進行していた部分から「手を付ける」(pick [something] back up) というような意味です。
もう一回お願いします

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "## 実現可能な解決方法"
ここのpossibleは、「可能か否か」のpossibleではなく、「いくつもある選択肢の内の一つ」の意味のpossibleです。
グーグル翻訳だと「考えられる解決策」でした。

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "幸いなことに、効果的な作業管理を助けるツールやパッケージがあります"
幸いなことに、効果的な作業管理を助け**てくれ**るツールやパッケージがあります

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"RStudioの最も有能て使えるもののひとつとして、プロジェクト管理機能が挙げられます。\n"
RStudioの最も有能**で**使える~~もの~~**機能**のひとつとして、プロジェクト管理機能が挙げられます

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"今日では、必要なものが揃い、再現可能なプロジェクトを作成するために、これが使われているのでしょう。"
今日~~で~~は、~~必要なものが揃い~~再現可能なプロジェクトを作成するために、~~これが~~**このプロジェクト管理機能を**使~~われているのでしょう~~**います**

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> ## チャレンジ：必要なものが揃ったプロジェクトを作成する"
self-contained の翻訳が難しいですね…
「必要なものが揃った」は少し違う気がするんですけど、他の言葉が思い浮かびません。
あとでイシューを開いておきます。

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"このプロジェクトについての全てのファイルは、このディレクトリにこれで全て揃うことになります。"
このプロジェクトに~~ついての~~**関わる**全てのファイルは、このディレクトリに~~これで全て揃う~~**保管・整理される**ことになります

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ですから、データは「読み込むだけ」のものと扱うのがよいというわけです。"
ですから、データは「読み込**み専用**~~むだけ~~」~~のもの~~と**して**扱うのがよいというわけです

「よい」の代わりに「理想的」もいいかもしれません

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"つまり、書いたものから生成できるようにしましょう。"
書いた~~もの~~**コード**から生成されたものは、全て捨てても良いものにしましょう。
つまり、書いた~~もの~~**コード**から生成できるようにしましょう

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"最終的なプロジェクトでは使われませんが、なかにはプロジェクト間で共有される分析もあるからです。"
~~そうすると後々楽になります~~。多くの分析は探索的なもので、最終的なプロジェクトでは使われませんが、なかにはプロジェクト間で共有される分析もある~~からです~~**ので、分析ごとに分けておくと後々探す時に楽になります。**

なぜこうすると楽になるのかを少し強調してみました。

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> [Good Enough Practices for Scientific Computing（科学的演算の良いと言えるやり方）](https://github.com/swcarpentry/good-enough-practices-in-scientific-computing/blob/gh-pages/good-enough-practices-for-scientific-co
プロジェクトの整理について薦めていることは以下のとおり**です**

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "Rで作業するより効果的な方法のひとつは、まず走らせたいコードを直接.Rスクリプトに書き、それから選択した行をインタラクティブなRコンソールで（RStudioのショートカットキーを使うか、「Run」ボタンをクリックして）走らせることです。"
僕は「走らす」でもいいんですけど、「実行する」のほうが合っているかもしれません。
お好きな方をどうぞ。（あとでイシューにも含めておきます）

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"プロジェクトが初期の段階にあるとき、最初の.Rスクリプトファイルには、直接実行されるコードの行が多数あるものである。\n"
プロジェクト~~が~~**の**初期~~の~~段階~~にあるとき~~**では**、最初の.Rスクリプトファイルには直接実行されるコードの行が多数あるもので~~ある~~**す**

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"プロジェクトが成熟していくと、何度も使える部分は、独自の関数としてまとめられる。\n"
「成熟」って普段では使わないので、変えさせてもらいます。

プロジェクトが~~成熟していくと~~**進むにつれて**、何度も使える部分は独自の関数としてまとめられ~~る~~ます

2019-07-25 10:04 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ショートカットを作ることで実現できます。"
この場合、ファイルシステム上で別の場所にあるファイルへの~~大事な~~ショートカット~~である~~**として**「symbolic links」を使うとよいでしょう。Linux 及び OS X では、`ln -s` コマンド~~が使え~~**で**、Windows~~で~~はWindowsのターミナルから`mklink` コマンド~~を使うか~~**で**、ショートカットを作ること~~で実現~~**が**できます

2019-07-27 05:51 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"最終的には、全てが少し混ざり合ってまとまっていくものです。"
科学的なプロセスは、徐々に進んでいくものです。プロジェクトの多くは、計画性のないメモやいくつかのコードから始まります。そして、草案ができ、最終的に、全てが少しづつ混ざり合ってまとまっていくのです。

2019-07-27 06:58 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"使ったコードを紐づけるのに、多分時間がいっぱいかかる"
探しているものを見つけたり、正しい図とその図を出力するコードの対応が分かるようになるのに、時間がかかることでしょう

2019-07-27 07:01 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "うまいプロジェクトのレイアウトは、結局のところ、自分自身を楽にする"
プロジェクトのレイアウトが良ければ、最終的に自分が楽になります

2019-07-27 07:03 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"* しばらく手をつけていなくても、プロジェクトのバックアップを簡単に選べる"
しばらく手をつけていなくても、簡単にプロジェクトを再開できます

2019-07-27 07:06 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "幸いなことに、効果的な作業管理を助けるツールやパッケージがあります"
嬉しいことに、作業管理を効率的にしてくれるツールやパッケージがあるのです

2019-07-27 07:07 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"RStudioの最も有能て使えるもののひとつとして、プロジェクト管理機能が挙げられます。\n"
RStudioの最も有能で使えるもの機能のひとつが、プロジェクト管理機能です

2019-07-27 07:13 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"今日では、必要なものが揃い、再現可能なプロジェクトを作成するために、これが使われているのでしょう。"
再現可能なプロジェクトを作成するために、今日はこのプロジェクト管理機能を使います

2019-07-27 07:17 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "> ## チャレンジ：必要なものが揃ったプロジェクトを作成する"
「それだけあれば良いタイプのプロジェクト」は、どうでしょう？
それかgoogle翻訳的に「自己完結型のプロジェクト」。

2019-07-27 07:18 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"このプロジェクトについての全てのファイルは、このディレクトリにこれで全て揃うことになります。"
このプロジェクトに関する全てのファイルは、このディレクトリに保管・整理されることになります

2019-07-27 07:23 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"つまり、書いたものから生成できるようにしましょう。"
生成って、表現古いでしょうか？「出力」の方が自然??
@DaichiSaitoAF, @atusy

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> ギャップマインダーのデータを[ここ](https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_wide.csv)ここからダウンロードしましょう"
```suggestion
msgstr "> ギャップマインダーのデータを[ここから](https://raw.githubusercontent.com/swcarpentry/r-novice-gapminder/gh-pages/_episodes_rmd/data/gapminder_wide.csv)ダウンロードしましょう"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 1. ファイルをダウンロードする（CTRL + S、右マウスクリック -> 「名前を付けて保存する」、またはファイル -> 「べーじを名前を付けて保存する」)\n"
```suggestion
"> 1. ファイルをダウンロードする（CTRL + S、右マウスクリック -> 「名前を付けて保存する」、またはファイル -> 「ページを名前を付けて保存する」)\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> このデータを後で読み込んで色々見てみます"
```suggestion
"> このデータは後で読み込んで色々調べます"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> データセットをよりよく理解しておくと、データセットをどうRに読み込むか決める際にそれが役に立ちます。"
```suggestion
msgstr "> データセットをよりよく理解しておくと、データセットをどうRに読み込むか決める際に役に立ちます。"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 次の疑問に回答するために、シェルのコマンドラインを使いましょう："
```suggestion
msgstr "> シェルのコマンドラインを使って、次の問題に答えて下さい："
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 1. ファイルのサイズは何か"
```suggestion
msgstr "> 1. ファイルのサイズは何ですか？"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 2. 列がいくつあるデータを持っているのか"
```suggestion
msgstr "> 2. データは何列入っていますか？"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 3. このファイルには、どのような値が保存されているか"
```suggestion
msgstr "> 3. ファイルには、どのような値が保存されていますか？"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これらのコマンドをシェルで走らせる：\n"
```suggestion
"> > 以下のコマンドをシェルで実行すれば答えられます：\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 1705行あり、データは次のような形をしている：\n"
```suggestion
"> > 1705行あり、データは次のような形をしています：\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> RStudioでは、メニュー項目の**Tools -> Shell...**を使って、シェルを素早く開くことができる。"
```suggestion
"> RStudioでは、メニュー項目の**Tools -> Shell...**を使って、シェルを素早く開くことができます。"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "プロジェクトでは、バージョン・コントロールを使うことが重要です。  次のリンクを参照 [RStudioでGitを使う良いレッスン](https://swcarpentry.github.io/git-novice/14-supplemental-rstudio/)."
```suggestion
msgstr "プロジェクトでは、バージョン・コントロールを使うことが重要です。 [RStudioでGitを使う良いレッスン](https://swcarpentry.github.io/git-novice/14-supplemental-rstudio/)を参照して下さい。"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"Rには、他のパッケージでもそうですが、関数についてヘルプファイルが用意されています。\n"
```suggestion
"R、そしてその他のパッケージには、関数のヘルプファイルが用意されています。\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"一般的に関数のヘルプを検索する構文は、（インタラクティブなRセッションで）自分の名前空間に読み込まれた\n"
```suggestion
"一般的な関数のヘルプを検索する構文は、（インタラクティブなRセッションで）自分の名前空間に読み込まれた\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"パッケージに存在する特定の関数が「function_name」の場合："
```suggestion
"パッケージに存在する特定の関数名、「function_name」を以下のように使って下さい："
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "これで、RStudioのヘルプページ（Rの場合は、画面に簡素なテキスト）が表示されます"
```suggestion
msgstr "これで、RStudioにヘルプページ（Rの場合は、画面に簡素なテキスト）が表示されます"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> Rの気が滅入る点は、かなり多くの使える関数があるという点です\n"
```suggestion
"> Rの気が滅入る点は、多くの関数があるという点です。\n"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 嬉しいことに、ヘルプファイルのおかげで、そんなことをせずに済むのです。"
```suggestion
"> 運の良いことに、ヘルプファイルのおかげでそんなことをせずに済みます。"
```

2019-08-04 10:33 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"多くのパッケージには、「ビニエット」があります。これは、使い方の説明や詳細な例を掲載する資料です。\n"
```suggestion
"多くのパッケージには、「ビニエット（vignette）」があります。これは、使い方の説明や詳細な例を掲載する資料です。\n"
```

2019-08-04 11:43 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> 嬉しいことに、ヘルプファイルのおかげで、そんなことをせずに済むのです。"
```suggestion
"> ありがたいことに、ヘルプファイルのおかげで、そんなことをせずに済むのです。"
```

「幸いなことに」、「運の良いことに」は、普段の会話であまり使わないので、よく使う「嬉しいことに」と訳しました。Luckilyのニュアンスは、「ありがたいことに」の方が、伝わるでしょうか？ @atusy @DaichiSaitoAF

2019-08-12 09:11 UTC, rikutakei requested changes
これで半分…かな？ :sweat_smile:

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ここから始めてみましょう。"
```suggestion
"このページから探し始めるといいかもしれません。"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "## コードがうまく動かない、つまり人の助けが必要なとき"
```suggestion
msgstr "## コードがうまく動作しない：人の助けが必要な場合"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"[CRAN Task Views](http://cran.at.r-project.org/web/views)を使うべきです。\n"
```suggestion
"[CRAN Task Views](http://cran.at.r-project.org/web/views)というページがあります。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"もし答えが見つからない場合、人に質問するのを助けるときに\n"
```suggestion
"もし答えが見つからない場合、人に質問をする際に\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"使える関数がいくつかあります："
```suggestion
"役に立つ関数がいくつかあります："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これで、使っているデータを誰でもコピー・アンド・ペーストしてRセッションで使える\n"
```suggestion
"これで、あなたが使っているデータを誰にでもコピー・アンド・ペーストしてRセッションで使える\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"形式に落とすことができます。"
落とすでも伝わると思うんですけど、あまり聞いたことがないような気がします。（知識不足かもしれませんが）

```suggestion
"形式にすることができます。"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これは、現在使っている R のバージョンを、読み込んでいるパッケージと共に表示させるものです。\n"
```suggestion
"これは、現在使っている R のバージョン、そして読み込まれている全てのパッケージを表示させる関数です。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"他の人が問題点を再現し、バグを見つける際に、この情報が役立つこともあります。"
```suggestion
"他の人が問題点を再現し、バグを見つける際にこの情報が役立つこともあります。"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 最初の事例では、要素は、整数型で、二番目の例では、文字列型、\n"
```suggestion
"> > 最初の事例では、要素は整数型で、二番目の例では文字列型、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 三番目の例は、文字列です。つまり、整数値は、「強制的に」\n"
```suggestion
"> > 三番目の例は文字列です。つまり、整数値は「強制的に」\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> `sep` と `collapse` の引数には、どんな違いがあるのでしょうか。\n"
```suggestion
"> `sep` と `collapse` の引数の違いは何でしょうか？\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > `paste`の関数は、長さも異なる引数をいくつも持つことができます。\n"
受けるのほうがacceptに近いと思います。受け取る、受け入れるもいいかもしれません。

```suggestion
"> > `paste`の関数は、長さも異なる引数をいくつでも受けることができます。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> ある関数（及び関連する母数を）を見つけるために、ヘルプを使いましょう。"
「ヘルプを使って、列が「\\t」（タブ）で区切られ、小数点が「．」（ピリオド）で分けられているcsvファイルを読み込む関数（及び関連する母数）を見つけて下さい。」

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 小数点は、「.」（ピリオド）となる関数です。この小数点以下を分けてる記号は、"
「国によって小数点を表す記号（コンマかピリオドか）が違うため、小数点以下を分けてる記号をチェックするのは、様々な国の人達と作業をする際など、特に重要になります。」

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> > *デフォルト*となっていますが、`comment.char` の引数を変更する必要があることもあります。"
```suggestion
msgstr "> > *デフォルト*となっていますが、データにハッシュ（#）の文字がある場合などは、`comment.char` の引数を変更する必要があることもあります。"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> `data/feline-data.csv` を作成する。"
```suggestion
"> `data/feline-data.csv` を作成することができます。"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "これを、以下を使ってRへ読み込ませる："
```suggestion
msgstr "以下を使って作ったデータをRへ読み込ませることができます："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データの列が区読文字で分けられたテキストファイルに収められた表形式データを、\n"
```suggestion
"データの列が区読文字で分けられたテキストファイルに収められた表形式データを\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"タブとカンマは、csvファイルでデータ点を区切る、又は分けるために使われる\n"
```suggestion
"タブとコンマは、csvファイルでデータ点を区切る、又は分けるために使われる\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"この `read.csv` の３つの関数が最も広く使われています。\n"
```suggestion
"これら３つの関数のうち、`read.csv` が最も広く使われています。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"必要があれば、 `read.csv` と `read.delim` の両方で、\n"
```suggestion
"必要であれば、 `read.csv` と `read.delim`、両方の\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "演算子 `$` を使って列を指定することで、列を抜き出し、すぐにデータセットを探索し始めることができます："
```suggestion
msgstr "演算子 `$` を使って列を指定し、列を抜き出すことで、すぐにデータセットの探索を始めることができます："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"## 計測された重さが２キロ少なかったことを発見したとしたら：\n"
```suggestion
"## 計測器が実際の重さより２キロ少なく測っていることが分かったとしたら：\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データ型が何かを聞くには："
```suggestion
"データ型が何かを知るには、以下を使います："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"なんと。この weight は、double型ではありません。 前にしたのと同じ計算をしようとすると、\n"
```suggestion
"なんと、この weight はdouble型ではないじゃありませんか！ 前と同じように計算をしようとすると、\n"
```

なんかオーバーリアクションですね :sweat_smile:
好きな方でいいと思います。

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"何が起こったのでしょうか。Rは、csvファイルをこれらの表のひとつに読み込む際、\n"
```suggestion
"何が起こったのでしょう？Rは、csvファイルをこれらの表のひとつに読み込む際、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"列にある全てのものが同じ基本の型であるべきと主張します。もし、列の*全て*が、\n"
```suggestion
"列にある全てのものが同じ基本の型であるべきだと主張します。もし、列の*全て*が、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"Rがあの猫のデータに読み込んだ表は、*data.frame（データフレーム）*と呼ばれるものでした。\n"
```suggestion
"Rが読み込んだ猫のデータ表は、*data.frame（データフレーム）*と呼ばれるもので、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"最初の例は、*data structure（データ構造）*、つまりRが基本的なデータ型から\n"
```suggestion
"*data structure（データ構造）*、つまりRが基本的なデータ型から構築できるデータの最初の例です。\n"
```

もうちょっと調整すればより伝わりやすくなるかな？

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データをうまくRで使うためには、何が基礎的なデータ構造か、それがどうふるまうか\n"
```suggestion
"データをうまくRで使うためには、基礎的なデータ構造、そしてその構造がどうふるまうか\n"
```
「ふるまう」⇒「動作する」でも伝わりますか？

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"を理解する必要があります。とりあえず、このことを掘り下げるために、あの猫のデータから\n"
```suggestion
"を理解する必要があります。より理解を深めるために、とりあえず猫のデータから\n"
```

while we investigate this behaviour furtherの訳が難しいですね。

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"もし、データ型を選ばなければ、デフォルトは、`logical`ですが、好きなデータ型を持つ空のベクトルを\n"
```suggestion
"もし、データ型を選ばなければ、デフォルトで`logical`になりますが、好きなデータ型を持つ空のベクトルを\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "ベクトルかどうかは："
```suggestion
msgstr "以下を使えばベクトルかどうかを確かめられます："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"このコマンドからの暗号みたいなアウトプットでは、このベクトルの基本データ型（ここでは `chr` つまり文字型）、\n"
```suggestion
"このコマンドから出てきた暗号みたいなアウトプットによると、このベクトルの基本データ型（ここでは `chr` （文字型））、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"もし単純にすると"
```suggestion
"`cats$weight`に同じようなことをすると："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"*Rに読み込んだデータの列data.framesは全てベクトル*で、\n"
```suggestion
"*Rのデータフレームに読み込まれたデータの列は全てベクトル*で、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"なぜRが、全ての列を同じ基本データ型にするのかの原因です。"
```suggestion
"Rが全ての列を同じ基本データ型にする理由です。"
```
原因だとRになにかしらの問題・バグがあるみたいに見えるので変えました

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > この整合性が、*きれいなデータ*と人々が言うときに意味していることなのです。\n"
```suggestion
"> > 人々が*きれいなデータ*のことを話している時は、この整合性を意味しているのです。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 長期的には、厳格な整合性が、後にRを使うのが楽になることに繋がります。 "
```suggestion
"> > 長期的には、この厳格な整合性が後にRを使うのが楽になることに繋がります。 "
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"なぜデータの基本データ型と、Rがそれをどう解釈しているかを知っておくべきかの理由です。\n"
```suggestion
"なぜ基本データ型と、Rがそれをどう解釈しているかを知っておくべきかの理由です。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"型強制が原因かもしれない。ベクトルの中、data.frameの列を全て同じ型にすること、\n"
```suggestion
"型強制が原因かもしれないという事です。ベクトルの中、データフレームの列を全て同じ型にすること、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"さもなくば、いやなサプライズが待っているだろう。"
```suggestion
"さもなくば、いやなサプライズに合う羽目になるかも！"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"しかし、強制がとても役立つこともあります。例えば、あの`cats` データの中にある、\n"
```suggestion
"しかし、型強制が役に立つこともあります。例えば、あの猫のデータの中にある、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"`likes_string` は数値型ですが、１と０が `TRUE` と `FALSE` （一般的に示しているもの）だと知っています。\n"
```suggestion
"`likes_string` は数値型ですが、私達は１と０が 一般的に`TRUE` と `FALSE`を示すことを知っています。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ここで、データが将に意味するところの`TRUE` 又は `FALSE` を持つ `logical` データ型を使わなければならないところ、 \n"
```suggestion
"ここで、データが将に意味するところの`TRUE` 又は `FALSE` を持つ `logical` データ型を使ったほうがいいに決まっています。 \n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +" `as.logical` 関数を使い、この列を `logical` へ '強制' できます："
```suggestion
" `as.logical` 関数を使い、この列を `logical` へ 「強制」 できます："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "先ほど、お伝えしたとおり、data.framesの列はベクトルです："
```suggestion
msgstr "先ほどお伝えしたとおり、データフレームの列はベクトルです："
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"しかし、それと同時に意外なこともしました、つまり、入力した文字列が表示される代わりに、\n"
```suggestion
"しかし、それと同時に意外なこともしました。入力した文字列が表示される代わりに、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"数字の塊がでてきたのです。Rは、人が読めるカテゴリーを、 内部で番号を振られた添字に変換したのです。\n"
```suggestion
"数字の羅列が出てきました。Rは、人が読めるカテゴリーを、 内部で番号を振られた添字に変換したのです。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 我々の `cats` data.frameは、順序なし因子でしょうか。名前は何でしょうか。\n"
```suggestion
"> 我々の `cats` データフレームには、順序なし因子がありますか？列の名前は何ですか？\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 試しに `?read.csv` を使って、どうやって文字の列を、順序なし因子ではなく、文字型ベクトルのまま\n"
```suggestion
"> `?read.csv` を使って、どうしたら文字の列を順序なし因子ではなく、文字型ベクトルのまま\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> とするかを見てみましょう。そして、`cats`の中の順序なし因子が、この方法で読み込まれたとき、\n"
```suggestion
"> 読み込む方法を見つけ出して下さい。そして、`cats`の中の順序なし因子がこの方法で読み込まれたとき、\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 文字型ベクトルになることを、ひとつかふたつコマンドを書いて示してみましょう。\n"
```suggestion
"> 順序なし因子ではなく文字型ベクトルであることを証明するコマンドを、ひとつかふたつ書いて下さい。\n"
```

2019-08-12 09:11 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 補足：新しい学習者は、ヘルプファイルを難しく感じるかもしれません。これはよくあることですので、\n"
```suggestion
"> > 補足：初めての方は、ヘルプファイルを難しく感じるかもしれません。これはよくあることですので、\n"
```

2019-08-12 09:11 UTC, rikutakei requested changes
これで半分…かな？ :sweat_smile:

2019-08-25 08:53 UTC, rikutakei requested changes
レッスン4と5ですね。

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"最初の順序なし因子であると仮定されていますが、デフォルトでは、順序なし因子は、\n"
```suggestion
"最初の順序なし因子が基準値であると仮定されていますが、デフォルトでは、順序なし因子は\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"アルファベット順に並べられています。水準の順位を指定することで、これを変更できます："
```suggestion
"アルファベット順に並べられています。水準の順位を指定することで、順序なし因子の順位を変更できます："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"この指定が、統計モデルの結果を解釈する際、本当にとても重要になりえます。"
```suggestion
"この指定が、統計モデルの結果を解釈する際、とても重要になりえます。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"小技袋に入れておきたいと思うはずのもう一つのデータ構造は、 `list` です。\n"
```suggestion
"覚えておきたいもう一つのデータ構造は、 `list` です。\n"
```
確かに "bag of tricks" =「小技袋」になるんですが、あまり聞いたことがないような…
「知恵袋」とかのほうが近いかも。おまかせします

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"リストは、他の種類よりも、ある意味シンプルです。その理由は、入れたいものを、\n"
```suggestion
"リストは、他の種類よりも、ある意味シンプルです。その理由は、入れたいものを\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "ここで、我々のdata.frameの少し驚くことが分かります。もし以下を走らせたらどうなるでしょう："
```suggestion
msgstr "これで、data.frameの驚くべき特徴を理解することができます。もし以下を走らせたらどうなるでしょう："
```
「驚くべき」いらないかもしれませんね

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"data.frame は、 'under the hood' のリストと同じように見えるでしょう。これは、data.frame が、\n"
"Under the hood" は「見えないところではこんな仕組みなんだよ」みたいな感じで使われます。

```suggestion
"data.frame は、 実際のところリストと同じように見えます。data.frame は、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"実際のところベクトルと順序なし因子のリストであり、そうでなくてはならないからです。\n"
```suggestion
"実際のところベクトルと順序なし因子のリストであり、これらから形成しなければならないからです。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ベクトルと順序なし因子が混ざった列を含むために、data.frame は、全ての列をひとまとめにし、\n"
```suggestion
"data.frame が、ベクトルと順序なし因子が混ざった列を含む全ての列をひとまとめにし、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"なじみのある表にするために、ベクトルよりも、もう少しやや柔軟である必要があるのです。\n"
```suggestion
"なじみのある表にするためには、ベクトルよりも柔軟な構造が必要だったのです。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"つまり、 `data.frame` は、全ての列の長さが同じでなければならない特別なリストなのです。"
```suggestion
"つまり、 `data.frame` は、全てのベクトルの長さが同じでなければならない特別なリストなのです。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> data.frames から、変数、観測値、要素を呼び出す方法はいくつかあります：\n"
```suggestion
"> data.frame から、変数、観測値、要素を呼び出す方法はいくつかあります：\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 上記の例を試してみて、それぞれで何が返ってくるかを説明してみましょう。\n"
```suggestion
"> 上記の例を試してみて、それぞれの例で何が返ってくるかを説明してみましょう。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> *ヒント：* 何がそれぞれ返ってくるかを確かめるために、関数 `typeof()` を使いましょう。\n"
```suggestion
"> *ヒント：* どういった値が返ってくるかを確かめるために、関数 `typeof()` を使いましょう。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > また、行と列の座標の入った角括弧を使いましょう。列の座標は\n"
```suggestion
"> > 同じ様に、行と列の座標の入った角括弧を使っています。列の座標は\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "最後に、重要な、行列を紹介します。全てが０の行列を宣言することができます："
```suggestion
msgstr "最後に、行列を紹介します。全てが０の行列を宣言できます："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> あっていましたか？なぜ（そうならなかった）でしょうか？\n"
```suggestion
"> 合っていましたか？なぜ答えが合っていた・合っていなかったのでしょうか？\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 行列は、属性の次元が追加されたベクトルですから、`length`は、\n"
```suggestion
"> > 行列は、次元が追加されたベクトルですので、`length`は\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> この `matrix` 関数は、デフォルトのように、行または列ごとに\n"
```suggestion
"> この `matrix` 関数は、デフォルトでは、行か列、どちらから\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> これがどう変化したか理解したか確認してみましょう。\n"
```suggestion
"> どうしたらこのデフォルト動作を変更できるか探してみて下さい。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > この `matrix` 関数は、デフォルトのように、行または列ごとに\n"
上記参照

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これがどう変化したか理解したか確認してみましょう。\n"
上記参照

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr ">  ワークショップのこのあたりで、それぞれのセクションのための文字型ベクトルを含む長さ２のリストを作ってみましょう："
ここ、ちょっとむずかしいですね。
このパート（chapter 4）の二つのセクション（「データ型」と「データ構造」）に該当する二つのベクトルを作って、それをリストに入れろ、ってことなんですけど、訳すとちょっとややこしいですね。

```suggestion
msgstr ">  ワークショップの現パート、それぞれのセクションのために、二つの文字型ベクトルが含まれるリストを作って下さい："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +">  データ構造で埋めてみましょう。\n"
```suggestion
">  データ構造で埋めてください。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 補足：ボードに長文のリストを作成したり、全ての型と構造を列挙したものを壁に\n"
```suggestion
"> > 補足：ボードや壁に、全ての型と構造を大きな文字で列挙したものを\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これを残りのワークショップのために残しておきましょう。\n"
```suggestion
"> > ワークショップが終わるまで残しておきましょう。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これで全て見たことになります。つまり、このレッスンで、Rの基本的なデータ型、データ構造をお示ししました。\n"
```suggestion
"これでRの基礎を全て見たことになります。このレッスンで、Rの基本的なデータ型、データ構造を習いました。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これからすることの全てが、これらの道具を用いた操作となります。\n"
```suggestion
"これからすることの全ては、これらの道具を用いた操作となります。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"しかし大抵の場合、一番の人気者はデータフレーム（CSVファイルから情報を読み込み作成する表）です。\n"
```suggestion
"しかし大抵の場合、主演はデータフレーム（CSVファイルから情報を読み込み作成した表）です。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ですので、新しい列を加えたい場合は、新しいベクトルを作ることあら始めることになります："
```suggestion
"ですので、新しい列を加えたい場合は、新しいベクトルを作ることから始めることになります："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> 3. `human_age` を、`as.numeric()` 関数を用いて、数値型に戻しましょう。そして、もともとの年に戻すために７で割りましょう。何が起こるでしょうか。"
```suggestion
msgstr "> 3. `human_age` を、`as.numeric()` 関数を用いて、数値型に戻しましょう。そして、もともとの年に戻すために７で割りましょう。何が起こったか説明して下さい。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 2. `human_age <- factor(human_age)`. `as.factor(human_age)` このままで、うまくいきます\n"
```suggestion
"> > 2. `human_age <- factor(human_age)`. `as.factor(human_age)` でもうまくいきます\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 3. `as.numeric(human_age)` からは、`1 2 3 4 4` が返ってきます。なぜなら、順序なし文字型は、それぞれが、ラベル（ここでは、28、35、56、63）に紐づけられた整数型（ここでは、1:4）として蓄積されているからです。順序なし文字型を数値型に変換する際は、ラベルの値ではなく、裏にある整数に変換されるのです。もとの数が欲しい場合は、`human_age
```suggestion
"> > 3. `as.numeric(human_age)` からは、`1 2 3 4 4` が返ってきます。なぜなら、順序なし文字型は、それぞれが、ラベル（ここでは、28、35、56、63）に紐づけられた整数型（ここでは、1:4）として蓄積されているからです。順序なし文字型を数値型に変換する際は、ラベルの値ではなく、裏にある整数に変換されるのです。もとの数が欲しい場合は、`human_age`を文字ベクトルにしてから、数値ベクトルにする必要があります（なぜこれでうまくいくのでしょう？）。この問題は、csvファイルの中で数だけを持つはずの列のどこかにうっかり文字を入れてしまい、データを読み込むとき`stringsAsFactors=FALSE`を設定し忘れてしまったときなどに起こります。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"Rのデータフレームに行列を加える方法は分かりましたが、「錆」猫データフレームに加える最初の試みで、\n"
```suggestion
"Rのデータフレームに行列を加える方法は分かりましたが、猫データフレームに\"tortoiseshell\"を加える最初の試みで、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "注意：ベクトルの中に行番号を入れれば、新しく追加した行の両方を削除することもできました：`cats[c(-4,-5), ]`"
```suggestion
msgstr "注意：ベクトルの中に行番号を入れれば、新しく追加した行を両方削除することもできす：`cats[c(-4,-5), ]`"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "データフレームの中で、列を削除することもできます。列「age」を削除したい場合はどうなるでしょう。この場合、要素番号か見出しを使う２つの方法があります。"
```suggestion
msgstr "データフレームから列を削除することもできます。列「age」を削除したい場合、どうすれば削除できるのでしょう。この場合、要素番号か見出しを使う２つの方法があります。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "## データフレームの追加"
```suggestion
msgstr "## データフレームへの追加"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データフレームんデータを加えるときに覚えておくべき重要なことは、*列は、ベクトルで、行はリスト* であることです。\n"
```suggestion
"データフレームにデータを加えるときに覚えておくべき重要なことは、*列はベクトルで、行はリスト* であることです。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "しかし、いまや行の名前は必要以上に複雑です。この列名を削除することができ、そうするとRは自動的に連続する名称をつけます。"
```suggestion
msgstr "しかし、いまや行の名前は必要以上に複雑です。この列名は削除することができます。削除すると、Rは自動的に連続する名称をつけます。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> * または、`read.csv` のファイルパスをウェブドレスに置き換えることでインターネットからRへ直接読み込むこともできます。こうすると、csvファイルのローカルコピーが、最初に自分のコンピューターに保存されないことに留意する必要があります。例えば、\n"
```suggestion
"> * または、`read.csv` のファイルパスをウェブアドレスに置き換えることで、インターネットからRへ直接読み込むこともできます。こうすると、csvファイルのローカルコピーが、最初に自分のコンピューターに保存されないことに留意する必要があります。例えば、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データがどうなっている`str`で見てみることです："
```suggestion
"データがどうなっているかを`str`で見てみることです："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データフレームを、その次元についての情報のために、色々見てみることもできます。\n"
```suggestion
"データフレームの次元について見てみることもできます。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"以下から何が出てくると思いますか。それはなぜですか。"
```suggestion
"以下から何が出てくると思いますか？それはなぜですか？"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"うまい予想は、データフレームの長さは行数（1704）だとするものですが、実はそうではありません。\n"
```suggestion
"予想としては、データフレームの長さは行数（1704）だと思うものですが、実はそうではありません。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "全ての列のタイトルを知り合いと思うことも多いでしょう、その場合、その後聞くこともできます："
```suggestion
msgstr "全ての列のタイトルを知りたいと思うことも多いと思うので、後で聞いてみましょう："
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"この段階で、Rが伝える構造が自分の直感や予想に合っているかを自問することが大切です。\n"
```suggestion
"この段階で、Rが伝える構造が自分の直感や予想と合っているかを自問することが大切です。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"それぞれの列の基本定なデータ型は、納得できるか、もしできないなら、今後、悪い驚きをもたらさないように、\n"
```suggestion
"それぞれの列の基本的なデータ型は、思った通りのデータ型になってますか？もしなっていないのなら、今後、予想外の事態を引き起こさないように、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"今の時点で、問題を解決しておく必要があります。そのためには、これまでRがどのようにデータを解釈するか学んだこと、\n"
```suggestion
"今の時点で、問題を解決しておく必要があります。そのためには、これまでに学んだ、Rがどのようにデータを解釈するか、\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"そして*厳格な整合性*がデータを記録する際に重要であることが生かせます。"
```suggestion
"そしてデータを記録する際の*厳格な整合性*の重要性といった知識を活かしましょう。"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データ型と構造は納得できると満足することができたら、データをちゃんと見てみる時間が始まります。\n"
```suggestion
"データ型と構造に満足することができたら、データを詳しく見始めることができます。\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 最後と中間のいくつかの行を確認するのは良い習慣です。なぜそうする必要があるのでしょうか。\n"
```suggestion
"> 最後と中間のいくつかの行を確認するのは良い習慣です。どうしたらこれらの行を見ることができるのでしょう？\n"
```

2019-08-25 08:53 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> バージョン管理を追加しましょう。\n"
```suggestion
"> バージョン管理に追加しましょう。\n"
```

2019-08-25 12:28 UTC, joelnitta requested changes
R-gapminderのレッスン２です

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"2. 幾つもの拡張ファイルを一緒に混ぜ合わせるため、\n"
```suggestion
"2. 幾つもの拡張子の異なるファイルを一緒に混ぜ合わせるため、\n"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "### データは読み込むだけにしましょう"
```suggestion
msgstr "### データは読み込み専用にしましょう"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"違うフォルダに保存し、「きれいにした」データセットを持つ２つめの「読み込むだけ」のデータを\n"
ここはもとの文書があまりうまく書けていないのが問題です。「汚いデータ」、「きれいなデータ」、「汚いデータをきれいにするコード」というフォルダが三つあるのか、「汚いデータ」、「きれいなデータと汚いデータをきれいにするコード」というフォルダが二つあるのか、はっきりしないですね。ま、後者にしてみたらどうかな？
```suggestion
"違うフォルダに保存し、「きれいにした」データセットをこのフォルダに\n"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"この作業は、「データ・マンジング」と呼ばれることもあります。 前処理で書いたものは、\n"
「もの」にすると、データを指しているのか、コード（scripts）を指しているのか、分かりづらいです。
```suggestion
"この作業は、「データ・マンジング」と呼ばれることもあります。 前処理で書いたコードは、\n"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"置くフォルダを作ると便利です。"
```suggestion
"置くと便利です。"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "## プロジェクト整理の最適なやり方"
```suggestion
msgstr "## プロジェクト管理の最適なやり方"
```

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"> 4. プロジェクトで書いたスクリプトとプログラムのソースは、`src` ディレクトリに、違うところから持ってきた、またはローカルで編集されたものは `bin` ディレクトリに置く\n"
"To compile software"の"compile"は「編集」でいいですか？「変換」ではないかな？
参考：https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%A9

2019-08-25 12:28 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"> 複数のプロジェクトで、同じデータや分析を使っていることに気づくことがあるかもしれません\n"
```suggestion
"> 複数のプロジェクトで、同じデータや分析のスクリプトを使っていることに気づくことがあるかもしれません\n"
```

2019-08-25 13:13 UTC, joelnitta requested changes
R-gapminderのレッスン３です。

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr " - Examples（例）：関数をどうやって使うかの例"
```suggestion
msgstr " - Examples（例）：関数の使い方の例"
```

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"関数やパッケージが分からない場合、分野ごとにまとめられたパッケージリストがまとめられている\n"
```suggestion
"関数やパッケージが分からない場合、[CRAN Task Views](http://cran.at.r-project.org/web/views)という\n"
```

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"[CRAN Task Views](http://cran.at.r-project.org/web/views)というページがあります。\n"
```suggestion
"分野ごとにまとめられたパッケージのリストがあります。\n"
```

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "## コードがうまく動作しない：人の助けが必要な場合"
"peers"はただの「他人」や「人」よりも、「同僚」とかが近い気がします。

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"もし答えが見つからない場合、人に質問をする際に\n"
（上と同様）

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"> > `paste`の関数は、長さも異なる引数をいくつも持つことができます。\n"
"can be a vector of any length"ですから、長さが必ずしも異なると限りません。
```suggestion
"> > `paste`の関数は、それぞれの長さと関係なく、引数をいくつも受けることができます。\n"
```

2019-08-25 13:13 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "> 小数点は、「.」（ピリオド）となる関数です。この小数点以下を分けてる記号は、"
「小数点以下を分けてる」ではなく、「小数点以下を分けて**い**る」（あるいは「分ける」）がいいと思います。

2019-09-01 10:17 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "## コードがうまく動作しない：人の助けが必要な場合"
```suggestion
msgstr "## コードがうまく動作しない：仲間の助けが必要な場合"
```

2019-09-01 10:21 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"もし答えが見つからない場合、人に質問をする際に\n"
```suggestion
"もし答えが見つからない場合、仲間に質問をする際に\n"
```

2019-09-01 10:32 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> 4. プロジェクトで書いたスクリプトとプログラムのソースは、`src` ディレクトリに、違うところから持ってきた、またはローカルで編集されたものは `bin` ディレクトリに置く\n"
```suggestion
"> 4. プロジェクトで書いたスクリプトとプログラムのソースは、`src` ディレクトリに、違うところから持ってきた、またはローカルで変換されたものは `bin` ディレクトリに置く\n"
```

2019-09-01 10:36 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> > `paste`の関数は、長さも異なる引数をいくつも持つことができます。\n"
```suggestion
"> > `paste`の関数は、それぞれの長さには関係なく、引数をいくつも受け入れることができます。\n"
```

2019-09-01 10:39 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "> ある関数（及び関連する母数を）を見つけるために、ヘルプを使いましょう。"
```suggestion
msgstr "> ヘルプを使って、列が「\t」（タブ）で区切られ、小数点が「．」（ピリオド）で分けられているcsvファイルを読み込む関数（及び関連する母数）を見つけて下さい。"
```

2019-09-01 10:42 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "> 小数点は、「.」（ピリオド）となる関数です。この小数点以下を分けてる記号は、"
```suggestion
msgstr "> 国によって小数点を表す記号（コンマかピリオドか）が違うため、小数点以下を分けている記号をチェックするのは、"
```

2019-09-01 10:43 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "> 特に様々な国の人達と作業をする場合、重要です。"
```suggestion
msgstr "> 様々な国の人達と作業をする際など、特に重要になります。"
```

2019-09-01 10:43 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +msgstr "> その理由は、国によって小数点を表す記号が違う"
```suggestion

```

2019-09-01 10:52 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"データをうまくRで使うためには、何が基礎的なデータ構造か、それがどうふるまうか\n"
```suggestion
"データをうまくRで使うためには、基礎的なデータ構造、そしてその構造がどう作用するか\n"
```

2019-09-01 11:00 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> > この整合性が、*きれいなデータ*と人々が言うときに意味していることなのです。\n"
> 
```suggestion
"> > 人々が*きれいなデータ*と話している時は、このように整合性のあるデータであることを意味しているのです。\n"
```

2019-09-01 11:03 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"さもなくば、いやなサプライズが待っているだろう。"
```suggestion
"さもなくば、いやなサプライズに会う羽目になるかもしれません。"
```

2019-09-01 11:14 UTC, joelnitta requested changes
R-gapminderのレッスン４です

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"何が起こったのでしょう？Rは、csvファイルをこれらの表のひとつに読み込む際、\n"
元の文章の文字通りな翻訳ではなくなりますが、この方がスッキリして分かりやすい気がします。
```suggestion
"何が起こったのでしょう？Rは、csvファイルを読み込む際、\n"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +msgstr "このふるまいをより理解するために、もう一つのデータ構造*ベクトル*を紹介します。"
ここも「動作」がいいと思います。
```suggestion
msgstr "この動作をより理解するために、もう一つのデータ構造*ベクトル*を紹介します。"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"なぜ基本データ型と、Rがそれをどう解釈しているかを知っておくべきかの理由です。\n"
```suggestion
"なぜ起こるのか、理解するには基本データ型とRがそれをどう解釈するかを知っておく必要があります。\n"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"ここでRは、我々のデータに３つのカテゴリーのどれかがあてはまるだろうことを知りました。\n"
```suggestion
"ここでRは、我々のデータに３つのカテゴリーが存在することに気づきました。\n"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"関数をモデリングする際、基準となっている水準の順位が何かを知っておくことが大事です。\n"
ここではmodellingは動詞としてではなく、形容詞として使われています。
```suggestion
"モデリングの関数を使う際、基準となっている水準の順位がどれかを知っておくことが大事です。\n"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"この指定が、統計モデルの結果を解釈する際、とても重要になりえます。"
「can be」のニュアンスはいらないと思います
```suggestion
"この指定が、統計モデルの結果を解釈する際、とても重要になります。"
```

2019-09-01 11:14 UTC, joelnitta commented on po/r-novice-gapminder.ja.po
> +"我々の `cats` の例では、整数、浮動小数、論理変数があります。\n"
前はdoubleをローマ字のままにしていました。どっちかに統一しましょう。

2019-09-03 13:29 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> バージョン管理を追加しましょう。\n"
"add it to version control"というのが、具体的にどういうことをするのかが、よく分かりませんでした。「バージョン管理」という場所があって、そこへ追加することなのでしょうか？ここは、「バージョン管理もしましょう」という意味でしょうか？
@rikutakei @joelnitta

2019-09-07 23:02 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> バージョン管理を追加しましょう。\n"
２つ目の「バージョン管理をしましょう」です。
Bash・Gitを習った後にRかPythonを習うので、バージョン管理を行う前提でレッスンを進めるはずです。
「ちゃんとバージョン管理をしましょうね」って感じです。
DataCarpentryかSWCか忘れたんですけど、RStudio内からGitをセットアップする項目があった気がします。
そこでセットアップする際にscriptsディレクトリをバージョン管理に追加するはずです。

2019-09-08 00:00 UTC, rikutakei requested changes
レッスン６のレビューです

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"どんなデータセットで複雑な演算をすることも簡単になります。"
```suggestion
"どんなデータセットにも複雑な演算を簡単にすることができます。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> Rでは、文字列、数値、論理値を含む単純なベクトルは、*原子（atomic）* ベクトルと呼ばれています。その理由は、それ以上、単純化できないベクトルだからです。"
```suggestion
"> Rでは、文字列、数値、論理値を含む単純なベクトルは、*原子（atomic）* ベクトルと呼ばれています。その理由は、原子ベクトルはそれ以上単純化できないからです。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "ちょっと触ってみるためのダミーベクトルを作ることができましたので、この中身をどういじってみましょうか。"
```suggestion
msgstr "ちょっと触ってみるためのダミーベクトルを作ることができたのですが、どうやってベクトルの中身を使うのでしょう？"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "ベクトルの要素を抽出するためには、対応する１から始まる要素番号が使えます："
```suggestion
msgstr "ベクトルの要素を抽出するためには、対応する１から始まる要素番号を使います："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"もし、負の番号をベクトルの要素番号として使った場合、Rは、指定された番号\n"
```suggestion
"もし、負の番号をベクトルの要素番号として使った場合、Rは指定された番号\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 正解は、関数を呼ぶ部分を括弧で囲むことで、\n"
```suggestion
"> 正解は、関数を呼ぶ部分を括弧で囲むことです。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 以下のアウトプットを得るために、少なくとも２つの異なるコマンドを思い出しましょう：\n"
```suggestion
"> 以下のアウトプットを得るために、少なくとも２つの異なるコマンドを考えてください：\n"
```
「思いつく」のほうが合ってるのかな？

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ２つの異なるコマンドを見つけた後、隣の人と結果を比べましょう。自分には違う案がありましたか？\n"
```suggestion
"> ２つの異なるコマンドを考えた後、隣の人と結果を比べましょう。自分とは違う案がでしたか？\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"オブジェクトの部分集合を作るには、この方法が通常より信頼できます：色々な要素の場所は、\n"
```suggestion
"オブジェクトの部分集合を作るには、この方法の方が確実なやり方です：要素の場所は、\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"部分集合の演算子を繋いで使うことで、よく変わります。\n"
```suggestion
"部分集合の演算子を繋いで使うことでよく変わるのですが。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"でも、名前はいつも同じです！"
```suggestion
"名前は変わらないのです！"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "論理ベクトルならどれでも部分集合を作ることができます："
```suggestion
msgstr "どんな論理ベクトルでも部分集合を作ることができます："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"分割することで、この宣言は、最初に `x>7` を計算し、論理ベクトル\n"
```suggestion
"分割すると、この宣言は、最初に `x>7` を計算し、論理ベクトル\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"（比較には、 `=` ではなく、 `==` を使わないといけなかったですよね）："
```suggestion
"（比較には、 `=` ではなく、 `==` を使わないといけません）："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 複数の論理基準を組み合わせたい場合がよくあります。\n"
```suggestion
"> 複数の論理基準を組み合わせたい場合はよくあります。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> Rにある論理ベクトルを複数組み合わせると：\n"
```suggestion
"> Rにが論理ベクトルを複数組み合わせる演算子があります：\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> プログラミングの際（つまり、ある宣言を実行するかどうかを決める際に）\n"
```suggestion
"> プログラミングの際に（つまり、ある宣言を実行するかどうかを決める際に）\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> だけ使うことがおすすめです。\n"
```suggestion
"> 使うことをおすすめします。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> （データフレームでは、--- Rは避けようとしますが、--- 列に同じ名前を付けることもできます。\n"
```suggestion
"> （データフレームでは、--- Rは避けようとしますが --- 列に同じ名前を付けることもできます。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 演算子を引用符で囲むことで、演算子についてのヘルプが探せることを覚えておきましょう：\n"
```suggestion
"> 演算子を引用符で囲むことで、演算子についてのヘルプを検索できることを覚えておきましょう：\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "複数の名前のある要素番号を飛ばすことは、それでも少し難しくなります。`\"a\"` と`\"c\"` の要素を削除したいとき、これを試してみます："
```suggestion
msgstr "複数の名前のある要素番号を飛ばすことは、少しですが、さらに難しくなります。`\"a\"` と`\"c\"` の要素を削除したいとき、以下を試したとしましょう："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "Rは *何か* をしましたが、注意しなければいけないという警告を出し、その結果はどうやら、*間違った回答*（`\"c\"` の要素が、ベクトルに含まれている）のようです！"
```suggestion
msgstr "Rは *何か* をしたのですが、私達が注目しなければならない警告も出しました。結果としては、どうやら *間違った回答* が帰ってきたみたいです（`\"c\"` の要素が、ベクトルに含まれています）！"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "ではいったい、 `!=` は、ここで実際に何をしたのでしょう。これは非常に素晴らしい質問です。"
```suggestion
msgstr "ではいったい、 `!=` は、ここで実際に何をしたのでしょう。これは素晴らしい質問です。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"違う長さのベクトルを比較しようとすると、何が起こるでしょうか？"
```suggestion
"違う長さのベクトルを比較しようとすると、何が起こるのでしょう？"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "もし、もう一つのベクトルよりも短いベクトルがあったとき、そのベクトルは、*再利用されます*："
```suggestion
msgstr "もし、もう一つのベクトルよりも短いベクトルがあったとき、そのベクトルは*再利用されます*："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"この場合、Rは `c(\"a\", \"c\")` を `names(x)` に合わせるのに必要なだけ**繰り返します**。つまり、`c(\"a\",\"c\",\"a\",\"c\",\"a\")`となります。\n"
```suggestion
"この場合、Rは `c(\"a\", \"c\")` を `names(x)` に合わせるのに必要な分だけ**繰り返します**。つまり、`c(\"a\",\"c\",\"a\",\"c\",\"a\")`となります。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"この場合、長い方のベクトルの長さ（５）は、短い方のベクトルの長さ（２）と一致しないので、Rは、警告メッセージを出力しました。もし、不運なことに、`names(x)` が、６つの要素を持っていたならば、Rは、*ひっそり* 間違った（意図していなかった）ことを行っていたでしょう。この再利用のルールは、見つけるのがとても難しく、とらえがたいバグをもたらすことがあります！"
```suggestion
"この場合、長い方のベクトルの長さ（５）は、短い方のベクトルの長さ（２）と一致しないので、Rは、警告メッセージを出力しました。もしも運悪く`names(x)` が６つの要素を持っていた場合、Rは*警告せずに* 間違った（意図していなかった）ことを行っていたでしょう。この再利用のルールは、見つけるのがとても難しく、とらえがたいバグをもたらすことがあります！"
```

ここは、Rが警告もせずに間違った事を実行するという非常に厄介なバグの良い例なので、警告が出るか出ないかを明確にしてみました。

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "Rに本当にやってもらいたいこと（左の引数の *それぞれの* 要素を、右の引数の要素の *全て* にマッチさせこと）を、してもらうには、 `%in%` 演算子を使う必要があります。`%in%` 演算子は、左の引数のそれぞれの要素、ここでは `x` の名前にひとつづつ 「この要素は、２番目の引数にあるかな」と尋ねていきます。ここで、値を *除く* ため、「中にある（in）」を「中にな
```suggestion
msgstr "Rに本当にやってもらいたいこと（左の引数の *それぞれの* 要素を、右の引数の要素の *全て* にマッチさせこと）をしてもらうには、 `%in%` 演算子を使う必要があります。`%in%` 演算子は、左の引数のそれぞれの要素、ここでは `x` の名前にひとつづつ 「この要素は、２番目の引数にあるかな」と尋ねていきます。ここで、値を *除く* ため、「中にある（in）」を「中にない（not in）」に変える `!` 演算子が必要です。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ベクトルの要素を選びましょう、要素のリストのどれかに該当するベクトルの要素を選ぶのは、\n"
```suggestion
"> データ分析をするにあたって、リスト内にある要素をベクトルの中から選択するのは\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> データ分析のタスクで、とてもよくあることです。例えば、gapminderのデータセットには、\n"
```suggestion
"> よくあることです。例えば、gapminderのデータセットには、\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> `国（country）` 及び `大陸（continent）` 変数があるけれども、これら２つのものさし\n"
```suggestion
"> `国（country）` 及び `大陸（continent）` 変数があるけれども、これら２つの目盛りの間\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> をつなぐ情報はありません。東南アジアの情報をひっぱってきたいとき、\n"
```suggestion
"> をつなぐ情報はありません。例えば東南アジアの情報を引き出したい場合、\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> どのように構築できるでしょうか。\n"
```suggestion
"> どのように構築するのでしょう？\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 警告が出てくる間違った方法（ `==` のみを使う）、\n"
```suggestion
"> 警告が出てくる、間違った方法（ `==` のみを使う）、\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 洗練された方法（ `%in%` を使う）方法があります。\n"
```suggestion
"> 洗練された方法（ `%in%` を使う）があります。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> この３つ全てを思いつき、それぞれがどう動く（動かない）か説明できたかを確認してみましょう。\n"
```suggestion
"> これら３つの方法それぞれの例を考え、それぞれがどう動く（動かない）か説明してください。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これは、正しい値を与えますが、これがどんなに変なものかが分かるといいのですが\n"
```suggestion
"> > これは正しい値を返すのですが、この方法がどれだけ不格好であるか理解できれば上出来です\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > （もし、もっと長いリストから国を選びたかったとしたら、どうすればよかったでしょう）。\n"
```suggestion
"> > （もっと長いリストから国を選ぶ場合は、この方法だったらどうなっていたでしょう？）。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > これは、正しいし、タイプする（読む）のも楽です。"
```suggestion
"> > 正しい回答でもあり、タイプする（読む）のも楽です。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +" * `na.omit` は、ベクトルから欠損値をフィルターし除きます"
```suggestion
" * `na.omit` は、ベクトルから欠損値をフィルターし、除きます"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これは、普通、役に立たず、読むのがわずらわしいです。しかし、行列は *列順序（column-major format）* で\n"
```suggestion
"これは、普段使うには役に立たず、読むときにも混乱を招きます。ですが、行列は *列順序（column-major format）* で\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"デフォルトは配置されることに注意しておくといいでしょう。つまり、ベクトルの要素は、列にある順番で配置されています。"
```suggestion
"デフォルト配置されるということを覚えておくといいでしょう。つまり、ベクトルの要素は、列にある順番で配置されています。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "もし、行列を、行の順番で埋めていきたい場合は、 `byrow=TRUE` が使えます："
```suggestion
msgstr "もし、行列を、行の順番で埋めていきたい場合は、 `byrow=TRUE` を使います："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 1. 次のうち、どのコマンドが、11と14を抜き出すことができるでしょうか\n"
```suggestion
"> 1. 次のコマンドのうち、11と14を抜き出すことができるコマンドはどれでしょう？\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"しかし、比較処理は、 反復的ではないため、使えません。比較処理は、リストのそれぞれの要素のデータ構造にある、個々の要素ではなく、\n"
```suggestion
"しかし、比較処理は 反復的ではないため、使えません。比較処理は、リストのそれぞれの要素のデータ構造にある、個々の要素ではなく、\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "または要素を飛ばすこともできません："
```suggestion
msgstr "また、要素を飛ばすこともできません："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"データフレームの中身は、リストなので、同じようなルールがあてはまることを覚えておきましょう。\n"
```suggestion
"データフレームの中身は実はリストなので、同じようなルールがあてはまることを覚えておきましょう。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"しかし、データフレームは、２次元のオブジェクトでもあります。"
```suggestion
"しかし、データフレームは２次元のオブジェクトでもあります。"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"1つの引数しかない `[` は、リストと同じような働きがあります、つまり、それぞれのリストの要素が列に対応します。\n"
```suggestion
"1つの引数しかない `[` は、リストと同じような働きがあり、それぞれのリストの要素が列に対応します。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"その結果のオブジェクトは、データフレームになるものです："
```suggestion
"その結果、返されるオブジェクトはデータフレームになります："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "２つの引数で、 `[` は、行列と同じような働きをします："
```suggestion
msgstr "２つの引数を使えば、 `[` は、行列と同じような働きをします："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"もし、１つの行を部分集合とする場合、結果は、データフレームになります\n"
```suggestion
"もし、１つの行を部分集合する場合、結果はデータフレームになります\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"（理由は、要素には色々な型があるからです）："
```suggestion
"（理由は、要素には色々なデータ型が混ざっているからです）："
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 1. なぜ、 `gapminder[1:20]` は、エラーを返すのでしょうか。 `gapminder[1:20, ]` とどう違うのでしょうか。\n"
```suggestion
"> 1. なぜ、 `gapminder[1:20]` は、エラーを返すのでしょうか？ `gapminder[1:20, ]` とどう違うのでしょう？\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 2. 新しい `gapminder_small` という1から9の行だけを含む `data.frame` を作りましょう。\n"
```suggestion
"> 2. 新しく `gapminder_small` という、1から9の行だけを含む `data.frame` を作ってください。\n"
```

2019-09-08 00:00 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 1.  `gapminder` は、データフレームなので、２つの次元の部分集合を作る必要があります。 `gapminder[1:20, ]` は、最初から20番目の行までについて全ての列を与えるでしょう。\n"
```suggestion
"> > 1.  `gapminder` は、データフレームなので、２つの次元の部分集合を作る必要があります。 `gapminder[1:20, ]` は、最初から20番目の行までについて全ての列を引き出します。\n"
```

2019-09-08 00:01 UTC, rikutakei requested changes
レッスン６のレビューです

2019-09-08 00:34 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> > この `matrix` 関数は、デフォルトのように、行または列ごとに\n"
```suggestion
"> > この `matrix` 関数は、デフォルトでは、行か列、どちらから\n"
```

2019-09-08 00:49 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> > これがどう変化したか理解したか確認してみましょう。\n"
```suggestion
"> > この `matrix` 関数は、デフォルトでは、行か列、どちらから\n"
```

2019-09-08 00:55 UTC, rikutakei requested changes
レッスン７のレビューです

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"コードを書くとき、実行の流れを制御したくなります。\n"
```suggestion
"コードを書く際、実行の流れを制御する必要がよくあります。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"あるいは、決まった回数、実行されるよう設定することもできます。"
```suggestion
"あるいは、決まった回数実行されるよう設定することもできます。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"条件付きの宣言で、最もよく使われる方法は、設計です："
```suggestion
"条件付きの宣言で、最もよく使われるのが「構文（constructs）」です："
```

プログラミングではConstruct は構文に訳されるみたいです

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "例えば、Rに、もし変数 `x` が、特定の値を持っていた場合、メッセージを表示させたいとします。"
```suggestion
msgstr "例えばRに、もし変数 `x` が特定の値を持っていた場合、メッセージを表示させたいとします。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "xは、10より大きくないため、表示された宣言は、コンソール上に表示されません。10より小さい場合に、違ったメッセージを表示させるためには、 `else` 宣言をいれなければなりません。"
```suggestion
msgstr "xは、10より大きくないため、表示された宣言はコンソール上に表示されません。10より小さい場合に違ったメッセージを表示させるためには、 `else` 宣言を追加しなければなりません。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"これが、初心者にとって頭の痛いことをもららすこともあります。例えば："
```suggestion
"初心者には複雑なので、混乱してしまうかもしれません。例えば："
```
確かに頭痛って書いてあるんですけど、いろいろと考えることがありすぎて頭が痛くなりそう、みたいな意味合いです。他にいい訳があれば変えてください

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 2012年について、同じことをしてみましょう。\n"
```suggestion
"> 2012年についても、同じことをしてください。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 適当なメッセージを表示しましょう。\n"
```suggestion
"> 適当なメッセージを表示してください。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 最初に、`gapminder$year` 中、どの要素が、 `2002` と等しいかを記した論理ベクトルを手に入れます：\n"
```suggestion
"> > 最初に、`gapminder$year` の内、どの要素が `2002` と等しいかを記した論理ベクトルを手に入れます：\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 2002年の記録が存在するということは、 `rows2002_number` が１以上あることと同じことです：\n"
```suggestion
"> > 2002年の記録が存在するということは、 `rows2002_number` が１以上あるということです：\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > 全てを一緒にすると、次の得ます：\n"
```suggestion
"> > 全てを合わせると、以下になります：\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "次のようなメッセージをもらった人はいますか。"
```suggestion
msgstr "次のような警告メッセージをもらった人はいますか？"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"関数 `if()` は、走りますが、最初の要素の条件だけを評価するでしょう。\n"
```suggestion
"関数 `if()` は走るのですが、最初の要素の条件しか評価しません。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 関数 `all()` は、その名前が示唆しているように、全ての値が `TRUE` である時のみ、\n"
```suggestion
"> 関数 `all()` は、その名前が示唆しているように、ベクトル内の全ての値が `TRUE` である時のみ、\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ベクトルは `TRUE` となります。"
```suggestion
"> `TRUE` となります。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "## 繰り返し処理"
```suggestion
msgstr "## 繰り返し行う処理"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"一連の値の間、繰り返しをしたい場合、\n"
```suggestion
"一連の値に繰り返し同じ演算をしたい場合、\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"繰り返す順番が重要で、それぞれに同じ演算を行うときは、 \n"
```suggestion
"そして繰り返す順番も重要である場合は、 \n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +" `for()` ループが、それをしてくれます。\n"
```suggestion
" `for()` ループを使いましょう。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr " `for()` ループを、もうひとつの `for()` ループと入れ子となる形にして、２つのことを同時に繰り返すこともできます。"
```suggestion
msgstr " `for()` ループを、もうひとつの `for()` ループと入れ子となる形にすれば、２つのことを同時に繰り返すこともできます。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "結果を表示させずに、ループの結果を新しいオブジェクトとして書くこともできました。"
```suggestion
msgstr "結果を表示させずに、ループの結果を新しいオブジェクトとして書くこともできます。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"ゆえに、多くの値の間、繰り返すときは、避けましょう。"
```suggestion
"ゆえに、多くの値の間を繰り返すときは避けましょう。"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> とてもよくありがちな、初心者と経験のあるRユーザーの両方の足を引っ張ることのひとつに、\n"
```suggestion
"> 初心者と経験のあるRユーザーの両方の足を引っ張るループの使い方の一つとして、\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 結果のオブジェクト（ベクトル、リスト、行列、データフレーム）をループ処理で作ろうとする\n"
```suggestion
"> 結果のオブジェクト（ベクトル、リスト、行列、データフレーム）をループするたびに作ってしまうという\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> コンピュータは、これを扱うのがとても下手で、計算が、速攻で\n"
```suggestion
"> コンピュータはこれを扱うのがとても下手で、すぐに計算が\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> のろのろ遅くなります。適当な次元を持つ空の結果オブジェクトを\n"
```suggestion
"> 遅くなります。適当な次元を持つ空の結果オブジェクトを\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 前もって宣言しておく方が絶対いいです。\n"
```suggestion
"> 前もって宣言しておく方が効率的です。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ０から１の間で乱数を生成するwhile ループをここで示しましょう。\n"
```suggestion
"> ０から１の間で乱数を生成します。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 例として、一様分布（`runif()` 関数）から0.1よりも小さい数を得るまで、\n"
```suggestion
"> 例として、このwhileループは一様分布（`runif()` 関数）から0.1よりも小さい数を得るまで、\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 同じですか。もし違ったら、なぜそうなったのでしょうか。\n"
```suggestion
"> 同じですか？もし違ったら、なぜそうなったのでしょう？\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> `output_vector2` の最後のコードのかたまりを、 `output_vector` と同じにするには、どう変えればよいでしょうか？\n"
```suggestion
"> `output_vector2` の最後のコードのかたまりを `output_vector` と同じにするには、どう変えればよいでしょうか？\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > **手順1**：大陸ベクトルから、確実に全ての唯一無二な値を抜き出せるかを是非確かめましょう。\n"
```suggestion
"> > **手順1**：大陸ベクトルから、確実に全ての唯一無二な値を抜き出せるかを確かめましょう。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ゆえに、 `if` 条件を、表示させる前につける必要があります。これは、演算された平均余命が、基準値以上か、未満かを判別し、結果によって、出力を表示させる必要があります。\n"
```suggestion
"> > ゆえに、 `if` 条件を、表示させる前につける必要があります。これは、演算された平均余命が基準値以上か、基準値未満かを判別し、結果によって出力を表示させる必要があります。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 今回は、平均余命は、50歳未満か、50歳以上70歳未満か、70歳以上か\n"
```suggestion
"> 今回は、平均余命は、50歳未満か、50歳以上70歳未満か、70歳以上かを\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ユニックス・シェルのレッスンで紹介した`grep` コマンドを「B」で始まる国を見つけるために使います。\n"
```suggestion
"> > シェルのレッスンで紹介した`grep` コマンドを「B」で始まる国を見つけるために使います。\n"
```

2019-09-08 00:55 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ユニックス・シェル節に従って、以下を試してみたいと思うかもしれません：\n"
```suggestion
"> > シェル節に従って、以下を試してみたいと思うかもしれません：\n"
```

2019-09-08 00:55 UTC, rikutakei requested changes
レッスン７のレビューです

2019-09-08 01:05 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"我々の `cats` の例では、整数、浮動小数、論理変数があります。\n"
```suggestion
"我々の `cats` の例では、, 整数型（integer）、浮動小数型（double）、論理型（logical）の変数があります。\n"
```

2019-09-08 01:18 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"> ２つの異なるコマンドを見つけた後、隣の人と結果を比べましょう。自分には違う案がありましたか？\n"
```suggestion
"> ２つの異なるコマンドを考えた後、隣の人と結果を比べましょう。自分とは違う案でしたか？\n"
```

2019-09-08 01:51 UTC, rkkmk commented on po/r-novice-gapminder.ja.po
> +"しかし、比較処理は、 反復的ではないため、使えません。比較処理は、リストのそれぞれの要素のデータ構造にある、個々の要素ではなく、\n"
```suggestion
"しかし、比較処理は反復的ではないため、使えません。比較処理は、リストのそれぞれの要素のデータ構造にある、個々の要素ではなく、\n"
```

2019-10-07 05:27 UTC, TomKellyGenetics commented
I'm okay to merge this if it's easier to submit or discuss further edits/revisions to each lesson separately. We could try separate edits to different lessons to separate branches but I don't think it's needed. Let's hold off on running scripts to update the markdown or HTML files and we can do this after merging all changes to the R lessons.Thanks for your efforts so far. Looks like it's coming along great!

2019-10-08 02:41 UTC, merged

2019-10-08 02:42 UTC, TomKellyGenetics commented
Sections 2, 3 and 4 have been reviewed and approved. Please submit PRs separately as per Issue #55. I hope we can keep up this great progress!