Translation of functions explained - r-novice-gapminder
swcarpentry-ja/i18n pull request #48
Opened 2019-08-08 21:20 UTC by atusy

2019-11-17 09:08 UTC, rikutakei requested changes
よく翻訳できてます。
細かいところを直してくれればすぐにマージできます。

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "> ## 関数とは何でしょうか？"
```suggestion
msgstr "> ## 関数とは何でしょう？"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"関数の中では関数を呼び出した相手に結果を遅るために [return\n"
```suggestion
"関数の中では関数を呼び出した相手に結果を送るために [return\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"このような検査は、プログラム実行を継続する前に現状が `TRUE` であることをアサートするので、アサーション文と呼ばれます。\n"
```suggestion
"このような検査は、プログラム実行を継続する前に現状が `TRUE` であることをアサート（表明・断言）するので、アサーション文と呼ばれます。\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"アサーション文により、エラーがどこで起きているか分かりやすくなりデバグが容易になります。"
```suggestion
"アサーション文により、エラーがどこで起きているか分かりやすくなりデバッグが容易になります。"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"エラーを返すためには、`stop` 関数が使えます。\n"
```suggestion
"エラーを返すためには、`stop` 関数を使います。\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"`stopifnot()` を用いて `fahr_to_kelvin()` に入力を検査するアサーションを追加し、\n"
```suggestion
"`stopifnot()` を用いて `fahr_to_kelvin()` に入力を検査するアサーション文を追加し、\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ## チャレンジの解答 3\n"
```suggestion
"> > ## チャレンジ３の解答\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ## チャレンジの解答 2\n"
```suggestion
"> > ## チャレンジ２の解答\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ## チャレンジの解答 1\n"
```suggestion
"> > ## チャレンジ１の解答\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"# データセットを受け取り人口の列と一人あたりのGDPをかけます。\n"
```suggestion
"# データセットを受け取り、人口の列と一人あたりのGDPをかけます。\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "代わりに `%in%` を使うと、`year` と `country` に複数の値を指定できるようになります。"
```suggestion
msgstr "代わりに `%in%` を使うことによって、`year` と `country` に複数の値を指定できるようになっています。"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> この挙動は \"値渡し\" と呼ばれコードの記述をより安全なものにします。\n"
```suggestion
"> この挙動は \"値渡し\" と呼ばれ、コードの記述をより安全なものにします。\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> 関数を実行している間だけ存在します。`calcGDP()` を呼ぶんだ時に、\n"
```suggestion
"> 関数を実行している間だけ存在します。`calcGDP()` を呼んだ時に、\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> > ## チャレンジの解答 4\n"
```suggestion
"> > ## チャレンジ４の解答\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +"> ここでは発展的な概念を知っておく必要のあること書きません。\n"
```suggestion
"> ここでは発展的な概念を知っておく必要のあることは書きません。\n"
```

2019-11-17 09:08 UTC, rikutakei commented on po/r-novice-gapminder.ja.po
> +msgstr "  - 何度のパラメータを変えながら実行するコードを関数にし、"
```suggestion
msgstr "  - 何度もパラメータを変えながら実行するコードを関数にし、"
```

2019-11-18 06:05 UTC, atusy commented
ありがとうございます。コミットしました。

2019-11-18 07:29 UTC, rikutakei approved these changes

2019-11-18 07:29 UTC, merged